// 颜色命名表（SSoT，2026-07-30 user 拍板）：xkcd 颜色调查（22 万人众包命名）按热度取
//   top 135、踢 15 条（粗俗名 + 近重复 navy/seafoam/mint/… + -ish 系模糊名）= 120 条。
//   锚点 RGB = xkcd 众包质心（比 CSS/X11 化石值更接近「大家说这个词时指的色」）；
//   顺序 = 热度降序——parse 撞名（尤其 tok 的合体词多锚点共用）时先到先得 = 最常用义胜出。
//
// 本地化拍板：**死字符串表，不走 t()/strings.ts**（图层名烘焙后不回译，机制不必进 i18n key 门）。
//   zh/ja = 逐条人工译名，**同语言内必须互异**（test 门死）；tok = ~20 个社区实际用法的合体词
//   （laso 同时盖蓝绿是这门语言的设计，多锚点撞同名是诚实翻译，不是缺陷——消费端撞名自己加序号）。
//
// 只放数据；查询（OKLab nearest / parse）在 color-name.ts。

export interface ColorNameEntry { en: string; zh: string; ja: string; tok: string; hex: string }

export const COLOR_NAMES: ColorNameEntry[] = [
  { en: "purple",           zh: "紫",       ja: "紫",             tok: "loje laso",        hex: "#7e1e9c" },
  { en: "green",            zh: "绿",       ja: "緑",             tok: "laso kasi",        hex: "#15b01a" },
  { en: "blue",             zh: "蓝",       ja: "青",             tok: "laso",             hex: "#0343df" },
  { en: "pink",             zh: "粉",       ja: "ピンク",         tok: "loje walo",        hex: "#ff81c0" },
  { en: "brown",            zh: "棕",       ja: "茶色",           tok: "loje pimeja",      hex: "#653700" },
  { en: "red",              zh: "红",       ja: "赤",             tok: "loje",             hex: "#e50000" },
  { en: "light blue",       zh: "浅蓝",     ja: "水色",           tok: "laso walo",        hex: "#95d0fc" },
  { en: "teal",             zh: "水鸭青",   ja: "ティール",       tok: "laso telo",        hex: "#029386" },
  { en: "orange",           zh: "橙",       ja: "オレンジ",       tok: "loje jelo",        hex: "#f97306" },
  { en: "light green",      zh: "浅绿",     ja: "薄緑",           tok: "laso walo",        hex: "#96f97b" },
  { en: "magenta",          zh: "品红",     ja: "マゼンタ",       tok: "loje laso",        hex: "#c20078" },
  { en: "yellow",           zh: "黄",       ja: "黄色",           tok: "jelo",             hex: "#ffff14" },
  { en: "sky blue",         zh: "天蓝",     ja: "空色",           tok: "laso sewi",        hex: "#75bbfd" },
  { en: "grey",             zh: "灰",       ja: "灰色",           tok: "walo pimeja",      hex: "#929591" },
  { en: "lime green",       zh: "酸橙绿",   ja: "ライムグリーン", tok: "laso jelo",        hex: "#89fe05" },
  { en: "light purple",     zh: "浅紫",     ja: "薄紫",           tok: "loje laso walo",   hex: "#bf77f6" },
  { en: "violet",           zh: "紫罗兰",   ja: "スミレ色",       tok: "loje laso",        hex: "#9a0eea" },
  { en: "dark green",       zh: "深绿",     ja: "深緑",           tok: "laso pimeja",      hex: "#033500" },
  { en: "turquoise",        zh: "绿松石",   ja: "ターコイズ",     tok: "laso telo",        hex: "#06c2ac" },
  { en: "lavender",         zh: "薰衣草紫", ja: "ラベンダー",     tok: "loje laso walo",   hex: "#c79fef" },
  { en: "dark blue",        zh: "深蓝",     ja: "暗い青",         tok: "laso pimeja",      hex: "#00035b" },
  { en: "tan",              zh: "棕褐",     ja: "タン",           tok: "jelo walo",        hex: "#d1b26f" },
  { en: "cyan",             zh: "青",       ja: "シアン",         tok: "laso telo",        hex: "#00ffff" },
  { en: "aqua",             zh: "水青",     ja: "アクア",         tok: "laso telo",        hex: "#13eac9" },
  { en: "forest green",     zh: "森林绿",   ja: "フォレストグリーン", tok: "laso pimeja",  hex: "#06470c" },
  { en: "mauve",            zh: "藕荷",     ja: "モーブ",         tok: "loje walo",        hex: "#ae7181" },
  { en: "dark purple",      zh: "深紫",     ja: "暗い紫",         tok: "loje laso pimeja", hex: "#35063e" },
  { en: "bright green",     zh: "亮绿",     ja: "明るい緑",       tok: "laso kasi",        hex: "#01ff07" },
  { en: "maroon",           zh: "栗红",     ja: "マルーン",       tok: "loje pimeja",      hex: "#650021" },
  { en: "olive",            zh: "橄榄",     ja: "オリーブ",       tok: "jelo pimeja",      hex: "#6e750e" },
  { en: "salmon",           zh: "鲑粉",     ja: "サーモン",       tok: "loje walo",        hex: "#ff796c" },
  { en: "beige",            zh: "米黄",     ja: "ベージュ",       tok: "jelo walo",        hex: "#e6daa6" },
  { en: "royal blue",       zh: "宝蓝",     ja: "ロイヤルブルー", tok: "laso",             hex: "#0504aa" },
  { en: "navy blue",        zh: "藏青",     ja: "紺",             tok: "laso pimeja",      hex: "#001146" },
  { en: "lilac",            zh: "丁香紫",   ja: "ライラック",     tok: "loje laso walo",   hex: "#cea2fd" },
  { en: "black",            zh: "黑",       ja: "黒",             tok: "pimeja",           hex: "#000000" },
  { en: "hot pink",         zh: "艳粉",     ja: "ホットピンク",   tok: "loje walo",        hex: "#ff028d" },
  { en: "light brown",      zh: "浅棕",     ja: "薄茶",           tok: "loje pimeja",      hex: "#ad8150" },
  { en: "pale green",       zh: "淡绿",     ja: "淡い緑",         tok: "laso walo",        hex: "#c7fdb5" },
  { en: "peach",            zh: "桃",       ja: "ピーチ",         tok: "loje jelo",        hex: "#ffb07c" },
  { en: "olive green",      zh: "橄榄绿",   ja: "オリーブグリーン", tok: "jelo pimeja",    hex: "#677a04" },
  { en: "dark pink",        zh: "深粉",     ja: "濃いピンク",     tok: "loje",             hex: "#cb416b" },
  { en: "periwinkle",       zh: "长春花蓝", ja: "ペリウィンクル", tok: "laso walo",        hex: "#8e82fe" },
  { en: "sea green",        zh: "海绿",     ja: "シーグリーン",   tok: "laso telo",        hex: "#53fca1" },
  { en: "lime",             zh: "青柠",     ja: "ライム",         tok: "laso jelo",        hex: "#aaff32" },
  { en: "indigo",           zh: "靛蓝",     ja: "藍色",           tok: "laso pimeja",      hex: "#380282" },
  { en: "mustard",          zh: "芥末黄",   ja: "マスタード",     tok: "jelo pimeja",      hex: "#ceb301" },
  { en: "light pink",       zh: "浅粉",     ja: "薄いピンク",     tok: "loje walo",        hex: "#ffd1df" },
  { en: "rose",             zh: "玫瑰",     ja: "ローズ",         tok: "loje walo",        hex: "#cf6275" },
  { en: "bright blue",      zh: "亮蓝",     ja: "明るい青",       tok: "laso",             hex: "#0165fc" },
  { en: "neon green",       zh: "荧光绿",   ja: "ネオングリーン", tok: "laso kasi",        hex: "#0cff0c" },
  { en: "burnt orange",     zh: "焦橙",     ja: "バーントオレンジ", tok: "loje jelo",      hex: "#c04e01" },
  { en: "aquamarine",       zh: "海蓝宝",   ja: "アクアマリン",   tok: "laso telo",        hex: "#04d8b2" },
  { en: "grass green",      zh: "草绿",     ja: "グラスグリーン", tok: "laso kasi",        hex: "#3f9b0b" },
  { en: "pale blue",        zh: "淡蓝",     ja: "淡い青",         tok: "laso walo",        hex: "#d0fefe" },
  { en: "dark red",         zh: "深红",     ja: "暗い赤",         tok: "loje pimeja",      hex: "#840000" },
  { en: "bright purple",    zh: "亮紫",     ja: "明るい紫",       tok: "loje laso",        hex: "#be03fd" },
  { en: "yellow green",     zh: "黄绿",     ja: "黄緑",           tok: "laso jelo",        hex: "#c0fb2d" },
  { en: "baby blue",        zh: "婴儿蓝",   ja: "ベビーブルー",   tok: "laso walo",        hex: "#a2cffe" },
  { en: "gold",             zh: "金",       ja: "金色",           tok: "jelo",             hex: "#dbb40c" },
  { en: "mint green",       zh: "薄荷绿",   ja: "ミントグリーン", tok: "laso walo",        hex: "#8fff9f" },
  { en: "plum",             zh: "李子紫",   ja: "プラム",         tok: "loje laso pimeja", hex: "#580f41" },
  { en: "royal purple",     zh: "帝王紫",   ja: "ロイヤルパープル", tok: "loje laso",      hex: "#4b006e" },
  { en: "brick red",        zh: "砖红",     ja: "レンガ色",       tok: "loje pimeja",      hex: "#8f1402" },
  { en: "dark teal",        zh: "深水鸭青", ja: "ダークティール", tok: "laso pimeja",      hex: "#014d4e" },
  { en: "burgundy",         zh: "酒红",     ja: "バーガンディ",   tok: "loje pimeja",      hex: "#610023" },
  { en: "khaki",            zh: "卡其",     ja: "カーキ",         tok: "jelo walo",        hex: "#aaa662" },
  { en: "blue green",       zh: "蓝绿",     ja: "青緑",           tok: "laso telo",        hex: "#137e6d" },
  { en: "seafoam green",    zh: "海沫绿",   ja: "シーフォームグリーン", tok: "laso walo",  hex: "#7af9ab" },
  { en: "kelly green",      zh: "凯利绿",   ja: "ケリーグリーン", tok: "laso kasi",        hex: "#02ab2e" },
  { en: "pea green",        zh: "豌豆绿",   ja: "ピーグリーン",   tok: "laso jelo",        hex: "#8eab12" },
  { en: "taupe",            zh: "灰褐",     ja: "トープ",         tok: "jelo walo",        hex: "#b9a281" },
  { en: "dark brown",       zh: "深棕",     ja: "焦茶",           tok: "loje pimeja",      hex: "#341c02" },
  { en: "deep purple",      zh: "黛紫",     ja: "深い紫",         tok: "loje laso pimeja", hex: "#36013f" },
  { en: "chartreuse",       zh: "查特绿",   ja: "シャルトルーズ", tok: "laso jelo",        hex: "#c1f80a" },
  { en: "bright pink",      zh: "亮粉",     ja: "明るいピンク",   tok: "loje walo",        hex: "#fe01b1" },
  { en: "light orange",     zh: "浅橙",     ja: "薄いオレンジ",   tok: "loje jelo",        hex: "#fdaa48" },
  { en: "pastel green",     zh: "粉彩绿",   ja: "パステルグリーン", tok: "laso walo",      hex: "#b0ff9d" },
  { en: "sand",             zh: "沙色",     ja: "砂色",           tok: "jelo walo",        hex: "#e2ca76" },
  { en: "dark orange",      zh: "深橙",     ja: "濃いオレンジ",   tok: "loje jelo",        hex: "#c65102" },
  { en: "spring green",     zh: "春绿",     ja: "若草色",         tok: "laso jelo",        hex: "#a9f971" },
  { en: "grey blue",        zh: "灰蓝",     ja: "グレーブルー",   tok: "laso",             hex: "#6b8ba4" },
  { en: "army green",       zh: "军绿",     ja: "アーミーグリーン", tok: "laso pimeja",    hex: "#4b5d16" },
  { en: "dark grey",        zh: "深灰",     ja: "暗い灰色",       tok: "walo pimeja",      hex: "#363737" },
  { en: "goldenrod",        zh: "金菊黄",   ja: "ゴールデンロッド", tok: "jelo",           hex: "#fac205" },
  { en: "slate",            zh: "板岩灰",   ja: "スレート",       tok: "walo pimeja",      hex: "#516572" },
  { en: "light teal",       zh: "浅水鸭青", ja: "ライトティール", tok: "laso walo",        hex: "#90e4c1" },
  { en: "rust",             zh: "铁锈红",   ja: "錆色",           tok: "loje pimeja",      hex: "#a83c09" },
  { en: "deep blue",        zh: "幽蓝",     ja: "深い青",         tok: "laso pimeja",      hex: "#040273" },
  { en: "pale pink",        zh: "淡粉",     ja: "淡いピンク",     tok: "loje walo",        hex: "#ffcfdc" },
  { en: "cerulean",         zh: "蔚蓝",     ja: "セルリアン",     tok: "laso",             hex: "#0485d1" },
  { en: "ochre",            zh: "赭黄",     ja: "オーカー",       tok: "jelo pimeja",      hex: "#bf9005" },
  { en: "pale yellow",      zh: "淡黄",     ja: "淡い黄色",       tok: "jelo walo",        hex: "#ffff84" },
  { en: "crimson",          zh: "绯红",     ja: "クリムゾン",     tok: "loje pimeja",      hex: "#8c000f" },
  { en: "fuchsia",          zh: "紫红",     ja: "フクシア",       tok: "loje laso",        hex: "#ed0dd9" },
  { en: "hunter green",     zh: "猎人绿",   ja: "ハンターグリーン", tok: "laso pimeja",    hex: "#0b4008" },
  { en: "slate blue",       zh: "板岩蓝",   ja: "スレートブルー", tok: "laso",             hex: "#5b7c99" },
  { en: "pale purple",      zh: "淡紫",     ja: "淡い紫",         tok: "loje laso walo",   hex: "#b790d4" },
  { en: "sea blue",         zh: "海蓝",     ja: "シーブルー",     tok: "laso",             hex: "#047495" },
  { en: "light grey",       zh: "浅灰",     ja: "薄い灰色",       tok: "walo",             hex: "#d8dcd6" },
  { en: "leaf green",       zh: "叶绿",     ja: "リーフグリーン", tok: "laso kasi",        hex: "#5ca904" },
  { en: "light yellow",     zh: "浅黄",     ja: "薄い黄色",       tok: "jelo walo",        hex: "#fffe7a" },
  { en: "eggplant",         zh: "茄紫",     ja: "茄子紺",         tok: "loje laso pimeja", hex: "#380835" },
  { en: "steel blue",       zh: "钢蓝",     ja: "スチールブルー", tok: "laso",             hex: "#5a7d9a" },
  { en: "moss green",       zh: "苔绿",     ja: "苔色",           tok: "laso kasi",        hex: "#658b38" },
  { en: "robin's egg blue", zh: "知更鸟蛋蓝", ja: "ロビンエッグブルー", tok: "laso sewi",  hex: "#98eff9" },
  { en: "white",            zh: "白",       ja: "白",             tok: "walo",             hex: "#ffffff" },
  { en: "grey green",       zh: "灰绿",     ja: "グレーグリーン", tok: "laso walo",        hex: "#789b73" },
  { en: "sage",             zh: "鼠尾草绿", ja: "セージ",         tok: "laso walo",        hex: "#87ae73" },
  { en: "burnt sienna",     zh: "赭石",     ja: "バーントシェンナ", tok: "loje pimeja",    hex: "#b04e0f" },
  { en: "reddish brown",    zh: "红棕",     ja: "赤茶",           tok: "loje pimeja",      hex: "#7f2b0a" },
  { en: "cream",            zh: "奶油",     ja: "クリーム",       tok: "jelo walo",        hex: "#ffffc2" },
  { en: "coral",            zh: "珊瑚",     ja: "サンゴ",         tok: "loje walo",        hex: "#fc5a50" },
  { en: "ocean blue",       zh: "海洋蓝",   ja: "オーシャンブルー", tok: "laso",           hex: "#03719c" },
  { en: "dark magenta",     zh: "深品红",   ja: "濃いマゼンタ",   tok: "loje laso",        hex: "#960056" },
  { en: "red orange",       zh: "红橙",     ja: "赤橙",           tok: "loje jelo",        hex: "#fd3c06" },
  { en: "midnight blue",    zh: "午夜蓝",   ja: "ミッドナイトブルー", tok: "laso pimeja",  hex: "#020035" },
  { en: "light violet",     zh: "浅紫罗兰", ja: "薄いスミレ色",   tok: "loje laso walo",   hex: "#d6b4fc" },
  { en: "dusty rose",       zh: "灰玫瑰",   ja: "ダスティローズ", tok: "loje walo",        hex: "#c0737a" },
  { en: "medium blue",      zh: "中蓝",     ja: "ミディアムブルー", tok: "laso",           hex: "#2c6fbb" },
];
