// 生成物 —— 勿手改，改 tools/gen-color-words.py（含 tok 手工小表）/ vendor/color-words/ 快照后重跑。
// 全语言统一色词表：行 = [类别, 名, hex, 别名(かな/拼音)?, slang?]。
// **行序 = parse 优先级**（mpl > css > en > zh > ja > tok，universal → 小众；同类别内 = 热度/表序）。
// 命名按用户选的 culture 过滤本表（默认按 UI 语言映射；slang 行 parse 照认、命名跳过）。
// 加新 culture = 只加行（消费端零 special-case）。档目：mpl 18 · css 148 · xkcd 949 · zh-trad 526 · ja-trad 462 · tok 26

/** 类别 = 命名 culture（或技术命名空间 mpl/css）。加新 culture 直接扩这个联合 + 加行。 */
export type ColorWordCat = "mpl" | "css" | "xkcd" | "zh-trad" | "ja-trad" | "tok";
/** [类别, 名, hex, 别名(かな/拼音)?, slang?] */
export type ColorWordRow = [ColorWordCat, string, string, string?, (0 | 1)?];

export const COLOR_WORDS: ColorWordRow[] = [
  ["mpl", "b", "#0000ff"],
  ["mpl", "g", "#008000"],
  ["mpl", "r", "#ff0000"],
  ["mpl", "c", "#00bfbf"],
  ["mpl", "m", "#bf00bf"],
  ["mpl", "y", "#bfbf00"],
  ["mpl", "k", "#000000"],
  ["mpl", "w", "#ffffff"],
  ["mpl", "tab:blue", "#1f77b4"],
  ["mpl", "tab:orange", "#ff7f0e"],
  ["mpl", "tab:green", "#2ca02c"],
  ["mpl", "tab:red", "#d62728"],
  ["mpl", "tab:purple", "#9467bd"],
  ["mpl", "tab:brown", "#8c564b"],
  ["mpl", "tab:pink", "#e377c2"],
  ["mpl", "tab:gray", "#7f7f7f"],
  ["mpl", "tab:olive", "#bcbd22"],
  ["mpl", "tab:cyan", "#17becf"],
  ["css", "aliceblue", "#f0f8ff"],
  ["css", "antiquewhite", "#faebd7"],
  ["css", "aqua", "#00ffff"],
  ["css", "aquamarine", "#7fffd4"],
  ["css", "azure", "#f0ffff"],
  ["css", "beige", "#f5f5dc"],
  ["css", "bisque", "#ffe4c4"],
  ["css", "black", "#000000"],
  ["css", "blanchedalmond", "#ffebcd"],
  ["css", "blue", "#0000ff"],
  ["css", "blueviolet", "#8a2be2"],
  ["css", "brown", "#a52a2a"],
  ["css", "burlywood", "#deb887"],
  ["css", "cadetblue", "#5f9ea0"],
  ["css", "chartreuse", "#7fff00"],
  ["css", "chocolate", "#d2691e"],
  ["css", "coral", "#ff7f50"],
  ["css", "cornflowerblue", "#6495ed"],
  ["css", "cornsilk", "#fff8dc"],
  ["css", "crimson", "#dc143c"],
  ["css", "cyan", "#00ffff"],
  ["css", "darkblue", "#00008b"],
  ["css", "darkcyan", "#008b8b"],
  ["css", "darkgoldenrod", "#b8860b"],
  ["css", "darkgray", "#a9a9a9"],
  ["css", "darkgreen", "#006400"],
  ["css", "darkgrey", "#a9a9a9"],
  ["css", "darkkhaki", "#bdb76b"],
  ["css", "darkmagenta", "#8b008b"],
  ["css", "darkolivegreen", "#556b2f"],
  ["css", "darkorange", "#ff8c00"],
  ["css", "darkorchid", "#9932cc"],
  ["css", "darkred", "#8b0000"],
  ["css", "darksalmon", "#e9967a"],
  ["css", "darkseagreen", "#8fbc8f"],
  ["css", "darkslateblue", "#483d8b"],
  ["css", "darkslategray", "#2f4f4f"],
  ["css", "darkslategrey", "#2f4f4f"],
  ["css", "darkturquoise", "#00ced1"],
  ["css", "darkviolet", "#9400d3"],
  ["css", "deeppink", "#ff1493"],
  ["css", "deepskyblue", "#00bfff"],
  ["css", "dimgray", "#696969"],
  ["css", "dimgrey", "#696969"],
  ["css", "dodgerblue", "#1e90ff"],
  ["css", "firebrick", "#b22222"],
  ["css", "floralwhite", "#fffaf0"],
  ["css", "forestgreen", "#228b22"],
  ["css", "fuchsia", "#ff00ff"],
  ["css", "gainsboro", "#dcdcdc"],
  ["css", "ghostwhite", "#f8f8ff"],
  ["css", "gold", "#ffd700"],
  ["css", "goldenrod", "#daa520"],
  ["css", "gray", "#808080"],
  ["css", "green", "#008000"],
  ["css", "greenyellow", "#adff2f"],
  ["css", "grey", "#808080"],
  ["css", "honeydew", "#f0fff0"],
  ["css", "hotpink", "#ff69b4"],
  ["css", "indianred", "#cd5c5c"],
  ["css", "indigo", "#4b0082"],
  ["css", "ivory", "#fffff0"],
  ["css", "khaki", "#f0e68c"],
  ["css", "lavender", "#e6e6fa"],
  ["css", "lavenderblush", "#fff0f5"],
  ["css", "lawngreen", "#7cfc00"],
  ["css", "lemonchiffon", "#fffacd"],
  ["css", "lightblue", "#add8e6"],
  ["css", "lightcoral", "#f08080"],
  ["css", "lightcyan", "#e0ffff"],
  ["css", "lightgoldenrodyellow", "#fafad2"],
  ["css", "lightgray", "#d3d3d3"],
  ["css", "lightgreen", "#90ee90"],
  ["css", "lightgrey", "#d3d3d3"],
  ["css", "lightpink", "#ffb6c1"],
  ["css", "lightsalmon", "#ffa07a"],
  ["css", "lightseagreen", "#20b2aa"],
  ["css", "lightskyblue", "#87cefa"],
  ["css", "lightslategray", "#778899"],
  ["css", "lightslategrey", "#778899"],
  ["css", "lightsteelblue", "#b0c4de"],
  ["css", "lightyellow", "#ffffe0"],
  ["css", "lime", "#00ff00"],
  ["css", "limegreen", "#32cd32"],
  ["css", "linen", "#faf0e6"],
  ["css", "magenta", "#ff00ff"],
  ["css", "maroon", "#800000"],
  ["css", "mediumaquamarine", "#66cdaa"],
  ["css", "mediumblue", "#0000cd"],
  ["css", "mediumorchid", "#ba55d3"],
  ["css", "mediumpurple", "#9370db"],
  ["css", "mediumseagreen", "#3cb371"],
  ["css", "mediumslateblue", "#7b68ee"],
  ["css", "mediumspringgreen", "#00fa9a"],
  ["css", "mediumturquoise", "#48d1cc"],
  ["css", "mediumvioletred", "#c71585"],
  ["css", "midnightblue", "#191970"],
  ["css", "mintcream", "#f5fffa"],
  ["css", "mistyrose", "#ffe4e1"],
  ["css", "moccasin", "#ffe4b5"],
  ["css", "navajowhite", "#ffdead"],
  ["css", "navy", "#000080"],
  ["css", "oldlace", "#fdf5e6"],
  ["css", "olive", "#808000"],
  ["css", "olivedrab", "#6b8e23"],
  ["css", "orange", "#ffa500"],
  ["css", "orangered", "#ff4500"],
  ["css", "orchid", "#da70d6"],
  ["css", "palegoldenrod", "#eee8aa"],
  ["css", "palegreen", "#98fb98"],
  ["css", "paleturquoise", "#afeeee"],
  ["css", "palevioletred", "#db7093"],
  ["css", "papayawhip", "#ffefd5"],
  ["css", "peachpuff", "#ffdab9"],
  ["css", "peru", "#cd853f"],
  ["css", "pink", "#ffc0cb"],
  ["css", "plum", "#dda0dd"],
  ["css", "powderblue", "#b0e0e6"],
  ["css", "purple", "#800080"],
  ["css", "rebeccapurple", "#663399"],
  ["css", "red", "#ff0000"],
  ["css", "rosybrown", "#bc8f8f"],
  ["css", "royalblue", "#4169e1"],
  ["css", "saddlebrown", "#8b4513"],
  ["css", "salmon", "#fa8072"],
  ["css", "sandybrown", "#f4a460"],
  ["css", "seagreen", "#2e8b57"],
  ["css", "seashell", "#fff5ee"],
  ["css", "sienna", "#a0522d"],
  ["css", "silver", "#c0c0c0"],
  ["css", "skyblue", "#87ceeb"],
  ["css", "slateblue", "#6a5acd"],
  ["css", "slategray", "#708090"],
  ["css", "slategrey", "#708090"],
  ["css", "snow", "#fffafa"],
  ["css", "springgreen", "#00ff7f"],
  ["css", "steelblue", "#4682b4"],
  ["css", "tan", "#d2b48c"],
  ["css", "teal", "#008080"],
  ["css", "thistle", "#d8bfd8"],
  ["css", "tomato", "#ff6347"],
  ["css", "turquoise", "#40e0d0"],
  ["css", "violet", "#ee82ee"],
  ["css", "wheat", "#f5deb3"],
  ["css", "white", "#ffffff"],
  ["css", "whitesmoke", "#f5f5f5"],
  ["css", "yellow", "#ffff00"],
  ["css", "yellowgreen", "#9acd32"],
  ["xkcd", "purple", "#7e1e9c"],
  ["xkcd", "green", "#15b01a"],
  ["xkcd", "blue", "#0343df"],
  ["xkcd", "pink", "#ff81c0"],
  ["xkcd", "brown", "#653700"],
  ["xkcd", "red", "#e50000"],
  ["xkcd", "light blue", "#95d0fc"],
  ["xkcd", "teal", "#029386"],
  ["xkcd", "orange", "#f97306"],
  ["xkcd", "light green", "#96f97b"],
  ["xkcd", "magenta", "#c20078"],
  ["xkcd", "yellow", "#ffff14"],
  ["xkcd", "sky blue", "#75bbfd"],
  ["xkcd", "grey", "#929591"],
  ["xkcd", "lime green", "#89fe05"],
  ["xkcd", "light purple", "#bf77f6"],
  ["xkcd", "violet", "#9a0eea"],
  ["xkcd", "dark green", "#033500"],
  ["xkcd", "turquoise", "#06c2ac"],
  ["xkcd", "lavender", "#c79fef"],
  ["xkcd", "dark blue", "#00035b"],
  ["xkcd", "tan", "#d1b26f"],
  ["xkcd", "cyan", "#00ffff"],
  ["xkcd", "aqua", "#13eac9"],
  ["xkcd", "forest green", "#06470c"],
  ["xkcd", "mauve", "#ae7181"],
  ["xkcd", "dark purple", "#35063e"],
  ["xkcd", "bright green", "#01ff07"],
  ["xkcd", "maroon", "#650021"],
  ["xkcd", "olive", "#6e750e"],
  ["xkcd", "salmon", "#ff796c"],
  ["xkcd", "beige", "#e6daa6"],
  ["xkcd", "royal blue", "#0504aa"],
  ["xkcd", "navy blue", "#001146"],
  ["xkcd", "lilac", "#cea2fd"],
  ["xkcd", "black", "#000000"],
  ["xkcd", "hot pink", "#ff028d"],
  ["xkcd", "light brown", "#ad8150"],
  ["xkcd", "pale green", "#c7fdb5"],
  ["xkcd", "peach", "#ffb07c"],
  ["xkcd", "olive green", "#677a04"],
  ["xkcd", "dark pink", "#cb416b"],
  ["xkcd", "periwinkle", "#8e82fe"],
  ["xkcd", "sea green", "#53fca1"],
  ["xkcd", "lime", "#aaff32"],
  ["xkcd", "indigo", "#380282"],
  ["xkcd", "mustard", "#ceb301"],
  ["xkcd", "light pink", "#ffd1df"],
  ["xkcd", "rose", "#cf6275"],
  ["xkcd", "bright blue", "#0165fc"],
  ["xkcd", "neon green", "#0cff0c"],
  ["xkcd", "burnt orange", "#c04e01"],
  ["xkcd", "aquamarine", "#04d8b2"],
  ["xkcd", "navy", "#01153e"],
  ["xkcd", "grass green", "#3f9b0b"],
  ["xkcd", "pale blue", "#d0fefe"],
  ["xkcd", "dark red", "#840000"],
  ["xkcd", "bright purple", "#be03fd"],
  ["xkcd", "yellow green", "#c0fb2d"],
  ["xkcd", "baby blue", "#a2cffe"],
  ["xkcd", "gold", "#dbb40c"],
  ["xkcd", "mint green", "#8fff9f"],
  ["xkcd", "plum", "#580f41"],
  ["xkcd", "royal purple", "#4b006e"],
  ["xkcd", "brick red", "#8f1402"],
  ["xkcd", "dark teal", "#014d4e"],
  ["xkcd", "burgundy", "#610023"],
  ["xkcd", "khaki", "#aaa662"],
  ["xkcd", "blue green", "#137e6d"],
  ["xkcd", "seafoam green", "#7af9ab"],
  ["xkcd", "kelly green", "#02ab2e"],
  ["xkcd", "puke green", "#9aae07", "", 1],
  ["xkcd", "pea green", "#8eab12"],
  ["xkcd", "taupe", "#b9a281"],
  ["xkcd", "dark brown", "#341c02"],
  ["xkcd", "deep purple", "#36013f"],
  ["xkcd", "chartreuse", "#c1f80a"],
  ["xkcd", "bright pink", "#fe01b1"],
  ["xkcd", "light orange", "#fdaa48"],
  ["xkcd", "mint", "#9ffeb0"],
  ["xkcd", "pastel green", "#b0ff9d"],
  ["xkcd", "sand", "#e2ca76"],
  ["xkcd", "dark orange", "#c65102"],
  ["xkcd", "spring green", "#a9f971"],
  ["xkcd", "puce", "#a57e52"],
  ["xkcd", "seafoam", "#80f9ad"],
  ["xkcd", "grey blue", "#6b8ba4"],
  ["xkcd", "army green", "#4b5d16"],
  ["xkcd", "dark grey", "#363737"],
  ["xkcd", "dark yellow", "#d5b60a"],
  ["xkcd", "goldenrod", "#fac205"],
  ["xkcd", "slate", "#516572"],
  ["xkcd", "light teal", "#90e4c1"],
  ["xkcd", "rust", "#a83c09"],
  ["xkcd", "deep blue", "#040273"],
  ["xkcd", "pale pink", "#ffcfdc"],
  ["xkcd", "cerulean", "#0485d1"],
  ["xkcd", "light red", "#ff474c"],
  ["xkcd", "mustard yellow", "#d2bd0a"],
  ["xkcd", "ochre", "#bf9005"],
  ["xkcd", "pale yellow", "#ffff84"],
  ["xkcd", "crimson", "#8c000f"],
  ["xkcd", "fuchsia", "#ed0dd9"],
  ["xkcd", "hunter green", "#0b4008"],
  ["xkcd", "blue grey", "#607c8e"],
  ["xkcd", "slate blue", "#5b7c99"],
  ["xkcd", "pale purple", "#b790d4"],
  ["xkcd", "sea blue", "#047495"],
  ["xkcd", "pinkish purple", "#d648d7"],
  ["xkcd", "puke", "#a5a502", "", 1],
  ["xkcd", "light grey", "#d8dcd6"],
  ["xkcd", "leaf green", "#5ca904"],
  ["xkcd", "light yellow", "#fffe7a"],
  ["xkcd", "eggplant", "#380835"],
  ["xkcd", "steel blue", "#5a7d9a"],
  ["xkcd", "moss green", "#658b38"],
  ["xkcd", "robin's egg blue", "#98eff9"],
  ["xkcd", "white", "#ffffff"],
  ["xkcd", "grey green", "#789b73"],
  ["xkcd", "sage", "#87ae73"],
  ["xkcd", "brick", "#a03623"],
  ["xkcd", "burnt sienna", "#b04e0f"],
  ["xkcd", "reddish brown", "#7f2b0a"],
  ["xkcd", "cream", "#ffffc2"],
  ["xkcd", "coral", "#fc5a50"],
  ["xkcd", "ocean blue", "#03719c"],
  ["xkcd", "greenish", "#40a368"],
  ["xkcd", "dark magenta", "#960056"],
  ["xkcd", "red orange", "#fd3c06"],
  ["xkcd", "bluish purple", "#703be7"],
  ["xkcd", "midnight blue", "#020035"],
  ["xkcd", "light violet", "#d6b4fc"],
  ["xkcd", "dusty rose", "#c0737a"],
  ["xkcd", "medium blue", "#2c6fbb"],
  ["xkcd", "greenish yellow", "#cdfd02"],
  ["xkcd", "yellowish green", "#b0dd16"],
  ["xkcd", "purplish blue", "#601ef9"],
  ["xkcd", "greyish blue", "#5e819d"],
  ["xkcd", "grape", "#6c3461"],
  ["xkcd", "light olive", "#acbf69"],
  ["xkcd", "cornflower blue", "#5170d7"],
  ["xkcd", "pinkish red", "#f10c45"],
  ["xkcd", "bright red", "#ff000d"],
  ["xkcd", "azure", "#069af3"],
  ["xkcd", "blue purple", "#5729ce"],
  ["xkcd", "dark turquoise", "#045c5a"],
  ["xkcd", "electric blue", "#0652ff"],
  ["xkcd", "off white", "#ffffe4"],
  ["xkcd", "powder blue", "#b1d1fc"],
  ["xkcd", "wine", "#80013f"],
  ["xkcd", "dull green", "#74a662"],
  ["xkcd", "apple green", "#76cd26"],
  ["xkcd", "light turquoise", "#7ef4cc"],
  ["xkcd", "neon purple", "#bc13fe"],
  ["xkcd", "cobalt", "#1e488f"],
  ["xkcd", "pinkish", "#d46a7e"],
  ["xkcd", "olive drab", "#6f7632"],
  ["xkcd", "dark cyan", "#0a888a"],
  ["xkcd", "purple blue", "#632de9"],
  ["xkcd", "dark violet", "#34013f"],
  ["xkcd", "dark lavender", "#856798"],
  ["xkcd", "forrest green", "#154406"],
  ["xkcd", "vomit", "#a2a415", "", 1],
  ["xkcd", "pale orange", "#ffa756"],
  ["xkcd", "greenish blue", "#0b8b87"],
  ["xkcd", "dark tan", "#af884a"],
  ["xkcd", "green blue", "#06b48b"],
  ["xkcd", "bluish green", "#10a674"],
  ["xkcd", "pastel blue", "#a2bffe"],
  ["xkcd", "moss", "#769958"],
  ["xkcd", "grass", "#5cac2d"],
  ["xkcd", "deep pink", "#cb0162"],
  ["xkcd", "blood red", "#980002"],
  ["xkcd", "sage green", "#88b378"],
  ["xkcd", "aqua blue", "#02d8e9"],
  ["xkcd", "terracotta", "#ca6641"],
  ["xkcd", "pastel purple", "#caa0ff"],
  ["xkcd", "sienna", "#a9561e"],
  ["xkcd", "dark olive", "#373e02"],
  ["xkcd", "green yellow", "#c9ff27"],
  ["xkcd", "scarlet", "#be0119"],
  ["xkcd", "greyish green", "#82a67d"],
  ["xkcd", "chocolate", "#3d1c02"],
  ["xkcd", "blue violet", "#5d06e9"],
  ["xkcd", "cornflower", "#6a79f7"],
  ["xkcd", "baby pink", "#ffb7ce"],
  ["xkcd", "charcoal", "#343837"],
  ["xkcd", "pine green", "#0a481e"],
  ["xkcd", "pumpkin", "#e17701"],
  ["xkcd", "greenish brown", "#696112"],
  ["xkcd", "red brown", "#8b2e16"],
  ["xkcd", "brownish green", "#6a6e09"],
  ["xkcd", "tangerine", "#ff9408"],
  ["xkcd", "salmon pink", "#fe7b7c"],
  ["xkcd", "aqua green", "#12e193"],
  ["xkcd", "raspberry", "#b00149"],
  ["xkcd", "greyish purple", "#887191"],
  ["xkcd", "rose pink", "#f7879a"],
  ["xkcd", "neon pink", "#fe019a"],
  ["xkcd", "cobalt blue", "#030aa7"],
  ["xkcd", "orange brown", "#be6400"],
  ["xkcd", "deep red", "#9a0200"],
  ["xkcd", "orange red", "#fd411e"],
  ["xkcd", "dirty yellow", "#cdc50a"],
  ["xkcd", "orchid", "#c875c4"],
  ["xkcd", "reddish pink", "#fe2c54"],
  ["xkcd", "reddish purple", "#910951"],
  ["xkcd", "yellow orange", "#fcb001"],
  ["xkcd", "light cyan", "#acfffc"],
  ["xkcd", "sky", "#82cafc"],
  ["xkcd", "light magenta", "#fa5ff7"],
  ["xkcd", "pale red", "#d9544d"],
  ["xkcd", "emerald", "#01a049"],
  ["xkcd", "dark beige", "#ac9362"],
  ["xkcd", "ugly green", "#7a9703", "", 1],
  ["xkcd", "jade", "#1fa774"],
  ["xkcd", "greenish grey", "#96ae8d"],
  ["xkcd", "dark salmon", "#c85a53"],
  ["xkcd", "purplish pink", "#ce5dae"],
  ["xkcd", "dark aqua", "#05696b"],
  ["xkcd", "brownish orange", "#cb7723"],
  ["xkcd", "light olive green", "#a4be5c"],
  ["xkcd", "light aqua", "#8cffdb"],
  ["xkcd", "clay", "#b66a50"],
  ["xkcd", "medium green", "#39ad48"],
  ["xkcd", "burnt umber", "#a0450e"],
  ["xkcd", "dull blue", "#49759c"],
  ["xkcd", "pale brown", "#b1916e"],
  ["xkcd", "emerald green", "#028f1e"],
  ["xkcd", "brownish", "#9c6d57"],
  ["xkcd", "mud", "#735c12"],
  ["xkcd", "dark rose", "#b5485d"],
  ["xkcd", "brownish red", "#9e3623"],
  ["xkcd", "pink purple", "#db4bda"],
  ["xkcd", "pinky purple", "#c94cbe"],
  ["xkcd", "camo green", "#526525"],
  ["xkcd", "faded green", "#7bb274"],
  ["xkcd", "dusty pink", "#d58a94"],
  ["xkcd", "purple pink", "#e03fd8"],
  ["xkcd", "vomit green", "#89a203", "", 1],
  ["xkcd", "deep green", "#02590f"],
  ["xkcd", "reddish orange", "#f8481c"],
  ["xkcd", "mahogany", "#4a0100"],
  ["xkcd", "aubergine", "#3d0734"],
  ["xkcd", "dull pink", "#d5869d"],
  ["xkcd", "evergreen", "#05472a"],
  ["xkcd", "dark sky blue", "#448ee4"],
  ["xkcd", "very light green", "#d1ffbd"],
  ["xkcd", "pastel pink", "#ffbacd"],
  ["xkcd", "grey purple", "#826d8c"],
  ["xkcd", "very light blue", "#d5ffff"],
  ["xkcd", "dark mauve", "#874c62"],
  ["xkcd", "cadet blue", "#4e7496"],
  ["xkcd", "ice blue", "#d7fffe"],
  ["xkcd", "light tan", "#fbeeac"],
  ["xkcd", "dirty green", "#667e2c"],
  ["xkcd", "neon blue", "#04d9ff"],
  ["xkcd", "wine red", "#7b0323"],
  ["xkcd", "chocolate brown", "#411900"],
  ["xkcd", "dull purple", "#84597e"],
  ["xkcd", "yellow brown", "#b79400"],
  ["xkcd", "denim", "#3b638c"],
  ["xkcd", "eggshell", "#ffffd4"],
  ["xkcd", "jungle green", "#048243"],
  ["xkcd", "dark peach", "#de7e5d"],
  ["xkcd", "poop", "#7f5e00", "", 1],
  ["xkcd", "umber", "#b26400"],
  ["xkcd", "light lavender", "#dfc5fe"],
  ["xkcd", "bright yellow", "#fffd01"],
  ["xkcd", "golden yellow", "#fec615"],
  ["xkcd", "dusty blue", "#5a86ad"],
  ["xkcd", "electric green", "#21fc0d"],
  ["xkcd", "lighter green", "#75fd63"],
  ["xkcd", "slate grey", "#59656d"],
  ["xkcd", "teal green", "#25a36f"],
  ["xkcd", "marine blue", "#01386a"],
  ["xkcd", "avocado", "#90b134"],
  ["xkcd", "terra cotta", "#c9643b"],
  ["xkcd", "dusty purple", "#825f87"],
  ["xkcd", "light maroon", "#a24857"],
  ["xkcd", "reddish", "#c44240"],
  ["xkcd", "dark lilac", "#9c6da5"],
  ["xkcd", "dark periwinkle", "#665fd1"],
  ["xkcd", "bluish grey", "#748b97"],
  ["xkcd", "puke yellow", "#c2be0e", "", 1],
  ["xkcd", "purplish", "#94568c"],
  ["xkcd", "ultramarine", "#2000b1"],
  ["xkcd", "barney purple", "#a00498"],
  ["xkcd", "forest", "#0b5509"],
  ["xkcd", "pea soup", "#929901"],
  ["xkcd", "brownish yellow", "#c9b003"],
  ["xkcd", "bright teal", "#01f9c6"],
  ["xkcd", "bluegreen", "#017a79"],
  ["xkcd", "green brown", "#544e03"],
  ["xkcd", "blurple", "#5539cc"],
  ["xkcd", "light sky blue", "#c6fcff"],
  ["xkcd", "periwinkle blue", "#8f99fb"],
  ["xkcd", "pale violet", "#ceaefa"],
  ["xkcd", "true blue", "#010fcc"],
  ["xkcd", "green grey", "#77926f"],
  ["xkcd", "grey brown", "#7f7053"],
  ["xkcd", "dark olive green", "#3c4d03"],
  ["xkcd", "apricot", "#ffb16d"],
  ["xkcd", "faded purple", "#916e99"],
  ["xkcd", "cerise", "#de0c62"],
  ["xkcd", "khaki green", "#728639"],
  ["xkcd", "burnt red", "#9f2305"],
  ["xkcd", "light forest green", "#4f9153"],
  ["xkcd", "violet blue", "#510ac9"],
  ["xkcd", "pale lavender", "#eecffe"],
  ["xkcd", "acid green", "#8ffe09"],
  ["xkcd", "purple grey", "#866f85"],
  ["xkcd", "lemon", "#fdff52"],
  ["xkcd", "bright orange", "#ff5b00"],
  ["xkcd", "soft green", "#6fc276"],
  ["xkcd", "blush", "#f29e8e"],
  ["xkcd", "yellowish brown", "#9b7a01"],
  ["xkcd", "fluorescent green", "#08ff08"],
  ["xkcd", "electric purple", "#aa23ff"],
  ["xkcd", "steel", "#738595"],
  ["xkcd", "dull orange", "#d8863b"],
  ["xkcd", "muddy green", "#657432"],
  ["xkcd", "marigold", "#fcc006"],
  ["xkcd", "ocean", "#017b92"],
  ["xkcd", "light mauve", "#c292a1"],
  ["xkcd", "bordeaux", "#7b002c"],
  ["xkcd", "light blue green", "#7efbb3"],
  ["xkcd", "yellowish", "#faee66"],
  ["xkcd", "snot green", "#9dc100", "", 1],
  ["xkcd", "light lime green", "#b9ff66"],
  ["xkcd", "drab green", "#749551"],
  ["xkcd", "faded blue", "#658cbb"],
  ["xkcd", "dark forest green", "#002d04"],
  ["xkcd", "hot purple", "#cb00f5"],
  ["xkcd", "dark maroon", "#3c0008"],
  ["xkcd", "brown green", "#706c11"],
  ["xkcd", "swamp green", "#748500"],
  ["xkcd", "light indigo", "#6d5acf"],
  ["xkcd", "purpley blue", "#5f34e7"],
  ["xkcd", "lightish blue", "#3d7afd"],
  ["xkcd", "teal blue", "#01889f"],
  ["xkcd", "denim blue", "#3b5b92"],
  ["xkcd", "dark lime green", "#7ebd01"],
  ["xkcd", "dull yellow", "#eedc5b"],
  ["xkcd", "pistachio", "#c0fa8b"],
  ["xkcd", "lemon yellow", "#fdff38"],
  ["xkcd", "red violet", "#9e0168"],
  ["xkcd", "dusky pink", "#cc7a8b"],
  ["xkcd", "dirt", "#8a6e45"],
  ["xkcd", "very dark green", "#062e03"],
  ["xkcd", "medium purple", "#9e43a2"],
  ["xkcd", "shit", "#7f5f00", "", 1],
  ["xkcd", "dark mustard", "#a88905"],
  ["xkcd", "pea soup green", "#94a617"],
  ["xkcd", "bubblegum pink", "#fe83cc"],
  ["xkcd", "barbie pink", "#fe46a5"],
  ["xkcd", "military green", "#667c3e"],
  ["xkcd", "pale teal", "#82cbb2"],
  ["xkcd", "bronze", "#a87900"],
  ["xkcd", "pinky red", "#fc2647"],
  ["xkcd", "dull red", "#bb3f3f"],
  ["xkcd", "darkish blue", "#014182"],
  ["xkcd", "bluish", "#2976bb"],
  ["xkcd", "dark gold", "#b59410"],
  ["xkcd", "yellowy green", "#bff128"],
  ["xkcd", "pine", "#2b5d34"],
  ["xkcd", "dark blue green", "#005249"],
  ["xkcd", "dirty pink", "#ca7b80"],
  ["xkcd", "slate green", "#658d6d"],
  ["xkcd", "prussian blue", "#004577"],
  ["xkcd", "bright violet", "#ad0afd"],
  ["xkcd", "lighter purple", "#a55af4"],
  ["xkcd", "steel grey", "#6f828a"],
  ["xkcd", "russet", "#a13905"],
  ["xkcd", "vermillion", "#f4320c"],
  ["xkcd", "greyish brown", "#7a6a4f"],
  ["xkcd", "red purple", "#820747"],
  ["xkcd", "red pink", "#fa2a55"],
  ["xkcd", "bright turquoise", "#0ffef9"],
  ["xkcd", "golden brown", "#b27a01"],
  ["xkcd", "cerulean blue", "#056eee"],
  ["xkcd", "soft blue", "#6488ea"],
  ["xkcd", "easter green", "#8cfd7e"],
  ["xkcd", "amber", "#feb308"],
  ["xkcd", "mid blue", "#276ab3"],
  ["xkcd", "shit brown", "#7b5804", "", 1],
  ["xkcd", "hospital green", "#9be5aa"],
  ["xkcd", "purpleish blue", "#6140ef"],
  ["xkcd", "purply blue", "#661aee"],
  ["xkcd", "silver", "#c5c9c7"],
  ["xkcd", "sickly green", "#94b21c"],
  ["xkcd", "melon", "#ff7855"],
  ["xkcd", "dusky rose", "#ba6873"],
  ["xkcd", "brown orange", "#b96902"],
  ["xkcd", "darkish green", "#287c37"],
  ["xkcd", "cranberry", "#9e003a"],
  ["xkcd", "purpleish", "#98568d"],
  ["xkcd", "ecru", "#feffca"],
  ["xkcd", "mocha", "#9d7651"],
  ["xkcd", "bright magenta", "#ff08e8"],
  ["xkcd", "coffee", "#a6814c"],
  ["xkcd", "sepia", "#985e2b"],
  ["xkcd", "faded red", "#d3494e"],
  ["xkcd", "canary yellow", "#fffe40"],
  ["xkcd", "bluey purple", "#6241c7"],
  ["xkcd", "pastel yellow", "#fffe71"],
  ["xkcd", "pale turquoise", "#a5fbd5"],
  ["xkcd", "greyish pink", "#c88d94"],
  ["xkcd", "marine", "#042e60"],
  ["xkcd", "purplish grey", "#7a687f"],
  ["xkcd", "camel", "#c69f59"],
  ["xkcd", "brownish grey", "#86775f"],
  ["xkcd", "burnt yellow", "#d5ab09"],
  ["xkcd", "cherry red", "#f7022a"],
  ["xkcd", "orangey brown", "#b16002"],
  ["xkcd", "soft pink", "#fdb0c0"],
  ["xkcd", "dark sea green", "#11875d"],
  ["xkcd", "aqua marine", "#2ee8bb"],
  ["xkcd", "robin egg blue", "#8af1fe"],
  ["xkcd", "light sea green", "#98f6b0"],
  ["xkcd", "mud brown", "#60460f"],
  ["xkcd", "sandstone", "#c9ae74"],
  ["xkcd", "british racing green", "#05480d"],
  ["xkcd", "faded pink", "#de9dac"],
  ["xkcd", "maize", "#f4d054"],
  ["xkcd", "ocre", "#c69c04"],
  ["xkcd", "orange yellow", "#ffad01"],
  ["xkcd", "dark khaki", "#9b8f55"],
  ["xkcd", "light lime", "#aefd6c"],
  ["xkcd", "bright light blue", "#26f7fd"],
  ["xkcd", "jade green", "#2baf6a"],
  ["xkcd", "barney", "#ac1db8"],
  ["xkcd", "adobe", "#bd6c48"],
  ["xkcd", "minty green", "#0bf77d"],
  ["xkcd", "light navy blue", "#2e5a88"],
  ["xkcd", "dusty green", "#76a973"],
  ["xkcd", "very dark blue", "#000133"],
  ["xkcd", "ocean green", "#3d9973"],
  ["xkcd", "mustard green", "#a8b504"],
  ["xkcd", "poop brown", "#7a5901", "", 1],
  ["xkcd", "olive brown", "#645403"],
  ["xkcd", "pink red", "#f5054f"],
  ["xkcd", "light navy", "#155084"],
  ["xkcd", "very light purple", "#f6cefc"],
  ["xkcd", "ivory", "#ffffcb"],
  ["xkcd", "bright lavender", "#c760ff"],
  ["xkcd", "bright aqua", "#0bf9ea"],
  ["xkcd", "robin's egg", "#6dedfd"],
  ["xkcd", "muted green", "#5fa052"],
  ["xkcd", "medium brown", "#7f5112"],
  ["xkcd", "copper", "#b66325"],
  ["xkcd", "dark lime", "#84b701"],
  ["xkcd", "strawberry", "#fb2943"],
  ["xkcd", "dirt brown", "#836539"],
  ["xkcd", "celery", "#c1fd95"],
  ["xkcd", "bright sky blue", "#02ccfe"],
  ["xkcd", "poo brown", "#885f01", "", 1],
  ["xkcd", "pinkish brown", "#b17261"],
  ["xkcd", "celadon", "#befdb7"],
  ["xkcd", "bright lime green", "#65fe08"],
  ["xkcd", "auburn", "#9a3001"],
  ["xkcd", "shocking pink", "#fe02a2"],
  ["xkcd", "mulberry", "#920a4e"],
  ["xkcd", "carolina blue", "#8ab8fe"],
  ["xkcd", "lightish green", "#61e160"],
  ["xkcd", "light lilac", "#edc8ff"],
  ["xkcd", "pale olive", "#b9cc81"],
  ["xkcd", "pumpkin orange", "#fb7d07"],
  ["xkcd", "yellow ochre", "#cb9d06"],
  ["xkcd", "fire engine red", "#fe0002"],
  ["xkcd", "deep sky blue", "#0d75f8"],
  ["xkcd", "watermelon", "#fd4659"],
  ["xkcd", "bottle green", "#044a05"],
  ["xkcd", "very dark purple", "#2a0134"],
  ["xkcd", "wheat", "#fbdd7e"],
  ["xkcd", "murky green", "#6c7a0e"],
  ["xkcd", "brownish purple", "#76424e"],
  ["xkcd", "kermit green", "#5cb200"],
  ["xkcd", "primary blue", "#0804f9"],
  ["xkcd", "orangey red", "#fa4224"],
  ["xkcd", "pale lilac", "#e4cbff"],
  ["xkcd", "rust red", "#aa2704"],
  ["xkcd", "dirty orange", "#c87606"],
  ["xkcd", "pinkish grey", "#c8aca9"],
  ["xkcd", "light plum", "#9d5783"],
  ["xkcd", "greeny blue", "#42b395"],
  ["xkcd", "dark navy", "#000435"],
  ["xkcd", "pink/purple", "#ef1de7"],
  ["xkcd", "irish green", "#019529"],
  ["xkcd", "baby poop", "#937c00", "", 1],
  ["xkcd", "slime green", "#99cc04"],
  ["xkcd", "purplish red", "#b0054b"],
  ["xkcd", "rouge", "#ab1239"],
  ["xkcd", "light rose", "#ffc5cb"],
  ["xkcd", "drab", "#828344"],
  ["xkcd", "dark navy blue", "#00022e"],
  ["xkcd", "light yellow green", "#ccfd7f"],
  ["xkcd", "easter purple", "#c071fe"],
  ["xkcd", "snot", "#acbb0d", "", 1],
  ["xkcd", "light salmon", "#fea993"],
  ["xkcd", "purpley pink", "#c83cb9"],
  ["xkcd", "poo", "#8f7303", "", 1],
  ["xkcd", "berry", "#990f4b"],
  ["xkcd", "medium grey", "#7d7f7c"],
  ["xkcd", "brown red", "#922b05"],
  ["xkcd", "blood", "#770001"],
  ["xkcd", "soft purple", "#a66fb5"],
  ["xkcd", "grey pink", "#c3909b"],
  ["xkcd", "bluey green", "#2bb179"],
  ["xkcd", "midnight", "#03012d"],
  ["xkcd", "dark indigo", "#1f0954"],
  ["xkcd", "warm grey", "#978a84"],
  ["xkcd", "sandy brown", "#c4a661"],
  ["xkcd", "cherry", "#cf0234"],
  ["xkcd", "blue/purple", "#5a06ef"],
  ["xkcd", "gunmetal", "#536267"],
  ["xkcd", "deep violet", "#490648"],
  ["xkcd", "tree green", "#2a7e19"],
  ["xkcd", "orangish brown", "#b25f03"],
  ["xkcd", "shamrock green", "#02c14d"],
  ["xkcd", "orangish red", "#f43605"],
  ["xkcd", "greeny yellow", "#c6f808"],
  ["xkcd", "ugly yellow", "#d0c101", "", 1],
  ["xkcd", "french blue", "#436bad"],
  ["xkcd", "dusky purple", "#895b7b"],
  ["xkcd", "butter yellow", "#fffd74"],
  ["xkcd", "light beige", "#fffeb6"],
  ["xkcd", "golden", "#f5bf03"],
  ["xkcd", "dusky blue", "#475f94"],
  ["xkcd", "lightblue", "#7bc8f6"],
  ["xkcd", "purply pink", "#f075e6"],
  ["xkcd", "off green", "#6ba353"],
  ["xkcd", "ocher", "#bf9b0c"],
  ["xkcd", "milk chocolate", "#7f4e1e"],
  ["xkcd", "light peach", "#ffd8b1"],
  ["xkcd", "deep magenta", "#a0025c"],
  ["xkcd", "caramel", "#af6f09"],
  ["xkcd", "greenish teal", "#32bf84"],
  ["xkcd", "pale lime", "#befd73"],
  ["xkcd", "purple red", "#990147"],
  ["xkcd", "blueberry", "#464196"],
  ["xkcd", "asparagus", "#77ab56"],
  ["xkcd", "pale grey", "#fdfdfe"],
  ["xkcd", "light grey blue", "#9dbcd4"],
  ["xkcd", "pale lime green", "#b1ff65"],
  ["xkcd", "grassy green", "#419c03"],
  ["xkcd", "mossy green", "#638b27"],
  ["xkcd", "earth", "#a2653e"],
  ["xkcd", "deep orange", "#dc4d01"],
  ["xkcd", "pale aqua", "#b8ffeb"],
  ["xkcd", "rose red", "#be013c"],
  ["xkcd", "stone", "#ada587"],
  ["xkcd", "rusty orange", "#cd5909"],
  ["xkcd", "pea", "#a4bf20"],
  ["xkcd", "sick green", "#9db92c"],
  ["xkcd", "chestnut", "#742802"],
  ["xkcd", "blue/green", "#0f9b8e"],
  ["xkcd", "amethyst", "#9b5fc0"],
  ["xkcd", "dark mint green", "#20c073"],
  ["xkcd", "pale rose", "#fdc1c5"],
  ["xkcd", "muted blue", "#3b719f"],
  ["xkcd", "fawn", "#cfaf7b"],
  ["xkcd", "buff", "#fef69e"],
  ["xkcd", "turquoise green", "#04f489"],
  ["xkcd", "muddy brown", "#886806"],
  ["xkcd", "sea", "#3c9992"],
  ["xkcd", "tomato", "#ef4026"],
  ["xkcd", "carnation pink", "#ff7fa7"],
  ["xkcd", "banana", "#ffff7e"],
  ["xkcd", "neon yellow", "#cfff04"],
  ["xkcd", "greyish", "#a8a495"],
  ["xkcd", "mid green", "#50a747"],
  ["xkcd", "muted purple", "#805b87"],
  ["xkcd", "electric pink", "#ff0490"],
  ["xkcd", "sandy", "#f1da7a"],
  ["xkcd", "ugly pink", "#cd7584", "", 1],
  ["xkcd", "turquoise blue", "#06b1c4"],
  ["xkcd", "light burgundy", "#a8415b"],
  ["xkcd", "greenish tan", "#bccb7a"],
  ["xkcd", "dark mint", "#48c072"],
  ["xkcd", "light urple", "#b36ff6"],
  ["xkcd", "midnight purple", "#280137"],
  ["xkcd", "pinkish orange", "#ff724c"],
  ["xkcd", "pear", "#cbf85f"],
  ["xkcd", "dark plum", "#3f012c"],
  ["xkcd", "tealish", "#24bca8"],
  ["xkcd", "perrywinkle", "#8f8ce7"],
  ["xkcd", "yellowish orange", "#ffab0f"],
  ["xkcd", "pastel orange", "#ff964f"],
  ["xkcd", "iris", "#6258c4"],
  ["xkcd", "ultramarine blue", "#1805db"],
  ["xkcd", "navy green", "#35530a"],
  ["xkcd", "seaweed", "#18d17b"],
  ["xkcd", "kiwi", "#9cef43"],
  ["xkcd", "fluro green", "#0aff02"],
  ["xkcd", "bright light green", "#2dfe54"],
  ["xkcd", "vivid green", "#2fef10"],
  ["xkcd", "frog green", "#58bc08"],
  ["xkcd", "dull brown", "#876e4b"],
  ["xkcd", "dusk", "#4e5481"],
  ["xkcd", "mustard brown", "#ac7e04"],
  ["xkcd", "leafy green", "#51b73b"],
  ["xkcd", "cool blue", "#4984b8"],
  ["xkcd", "almost black", "#070d0d"],
  ["xkcd", "yellow/green", "#c8fd3d"],
  ["xkcd", "heliotrope", "#d94ff5"],
  ["xkcd", "green apple", "#5edc1f"],
  ["xkcd", "baby poop green", "#8f9805", "", 1],
  ["xkcd", "apple", "#6ecb3c"],
  ["xkcd", "purpleish pink", "#df4ec8"],
  ["xkcd", "night blue", "#040348"],
  ["xkcd", "merlot", "#730039"],
  ["xkcd", "lightgreen", "#76ff7b"],
  ["xkcd", "tomato red", "#ec2d01"],
  ["xkcd", "key lime", "#aeff6e"],
  ["xkcd", "pale cyan", "#b7fffa"],
  ["xkcd", "vomit yellow", "#c7c10c", "", 1],
  ["xkcd", "purplish brown", "#6b4247"],
  ["xkcd", "bubblegum", "#ff6cb5"],
  ["xkcd", "shamrock", "#01b44c"],
  ["xkcd", "mango", "#ffa62b"],
  ["xkcd", "lime yellow", "#d0fe1d"],
  ["xkcd", "hot green", "#25ff29"],
  ["xkcd", "grape purple", "#5d1451"],
  ["xkcd", "faded orange", "#f0944d"],
  ["xkcd", "avocado green", "#87a922"],
  ["xkcd", "peacock blue", "#016795"],
  ["xkcd", "weird green", "#3ae57f"],
  ["xkcd", "bright lilac", "#c95efb"],
  ["xkcd", "fern green", "#548d44"],
  ["xkcd", "dirty blue", "#3f829d"],
  ["xkcd", "rust orange", "#c45508"],
  ["xkcd", "heather", "#a484ac"],
  ["xkcd", "deep teal", "#00555a"],
  ["xkcd", "dark seafoam", "#1fb57a"],
  ["xkcd", "baby poo", "#ab9004", "", 1],
  ["xkcd", "yellowgreen", "#bbf90f"],
  ["xkcd", "light sage", "#bcecac"],
  ["xkcd", "light aquamarine", "#7bfdc7"],
  ["xkcd", "spearmint", "#1ef876"],
  ["xkcd", "bright lime", "#87fd05"],
  ["xkcd", "vibrant green", "#0add08"],
  ["xkcd", "very pale green", "#cffdbc"],
  ["xkcd", "faded yellow", "#feff7f"],
  ["xkcd", "bile", "#b5c306", "", 1],
  ["xkcd", "viridian", "#1e9167"],
  ["xkcd", "very light pink", "#fff4f2"],
  ["xkcd", "puke brown", "#947706", "", 1],
  ["xkcd", "medium pink", "#f36196"],
  ["xkcd", "ugly purple", "#a442a0", "", 1],
  ["xkcd", "sunshine yellow", "#fffd37"],
  ["xkcd", "seaweed green", "#35ad6b"],
  ["xkcd", "light periwinkle", "#c1c6fc"],
  ["xkcd", "lemon green", "#adf802"],
  ["xkcd", "greeny brown", "#696006"],
  ["xkcd", "dark grey blue", "#29465b"],
  ["xkcd", "bright olive", "#9cbb04"],
  ["xkcd", "turtle green", "#75b84f"],
  ["xkcd", "pale sky blue", "#bdf6fe"],
  ["xkcd", "light mustard", "#f7d560"],
  ["xkcd", "diarrhea", "#9f8303", "", 1],
  ["xkcd", "dark aquamarine", "#017371"],
  ["xkcd", "brownish pink", "#c27e79"],
  ["xkcd", "baby shit green", "#889717", "", 1],
  ["xkcd", "purpley", "#8756e4"],
  ["xkcd", "greyblue", "#77a1b5"],
  ["xkcd", "hot magenta", "#f504c9"],
  ["xkcd", "blue/grey", "#758da3"],
  ["xkcd", "pale", "#fff9d0"],
  ["xkcd", "cool green", "#33b864"],
  ["xkcd", "sandy yellow", "#fdee73"],
  ["xkcd", "eggshell blue", "#c4fff7"],
  ["xkcd", "barf green", "#94ac02", "", 1],
  ["xkcd", "baby green", "#8cff9e"],
  ["xkcd", "vibrant purple", "#ad03de"],
  ["xkcd", "brown grey", "#8d8468"],
  ["xkcd", "water blue", "#0e87cc"],
  ["xkcd", "lipstick red", "#c0022f"],
  ["xkcd", "banana yellow", "#fafe4b"],
  ["xkcd", "wisteria", "#a87dc2"],
  ["xkcd", "purple brown", "#673a3f"],
  ["xkcd", "brown yellow", "#b29705"],
  ["xkcd", "purple/pink", "#d725de"],
  ["xkcd", "lemon lime", "#bffe28"],
  ["xkcd", "grey/blue", "#647d8e"],
  ["xkcd", "dusty red", "#b9484e"],
  ["xkcd", "deep rose", "#c74767"],
  ["xkcd", "dark seafoam green", "#3eaf76"],
  ["xkcd", "muddy yellow", "#bfac05"],
  ["xkcd", "carnation", "#fd798f"],
  ["xkcd", "yellowy brown", "#ae8b0c"],
  ["xkcd", "violet red", "#a50055"],
  ["xkcd", "twilight blue", "#0a437a"],
  ["xkcd", "pure blue", "#0203e2"],
  ["xkcd", "lightish red", "#fe2f4a"],
  ["xkcd", "brick orange", "#c14a09"],
  ["xkcd", "velvet", "#750851"],
  ["xkcd", "sunflower", "#ffc512"],
  ["xkcd", "light mint green", "#a6fbb2"],
  ["xkcd", "light grass green", "#9af764"],
  ["xkcd", "lavender blue", "#8b88f8"],
  ["xkcd", "rusty red", "#af2f0d"],
  ["xkcd", "lightish purple", "#a552e6"],
  ["xkcd", "dried blood", "#4b0101"],
  ["xkcd", "light blue grey", "#b7c9e2"],
  ["xkcd", "leaf", "#71aa34"],
  ["xkcd", "orangish", "#fc824a"],
  ["xkcd", "pale olive green", "#b1d27b"],
  ["xkcd", "off yellow", "#f1f33f"],
  ["xkcd", "dusty orange", "#f0833a"],
  ["xkcd", "butter", "#ffff81"],
  ["xkcd", "royal", "#0c1793"],
  ["xkcd", "petrol", "#005f6a"],
  ["xkcd", "greenish cyan", "#2afeb7"],
  ["xkcd", "duck egg blue", "#c3fbf4"],
  ["xkcd", "bubble gum pink", "#ff69af"],
  ["xkcd", "bluegrey", "#85a3b2"],
  ["xkcd", "warm brown", "#964e02"],
  ["xkcd", "twilight", "#4e518b"],
  ["xkcd", "saffron", "#feb209"],
  ["xkcd", "purple/blue", "#5d21d0"],
  ["xkcd", "dark sand", "#a88f59"],
  ["xkcd", "vibrant blue", "#0339f8"],
  ["xkcd", "putty", "#beae8a"],
  ["xkcd", "lawn green", "#4da409"],
  ["xkcd", "camouflage green", "#4b6113"],
  ["xkcd", "blush pink", "#fe828c"],
  ["xkcd", "reddy brown", "#6e1005"],
  ["xkcd", "darkish red", "#a90308"],
  ["xkcd", "algae green", "#21c36f"],
  ["xkcd", "dark coral", "#cf524e"],
  ["xkcd", "bright cyan", "#41fdfe"],
  ["xkcd", "piss yellow", "#ddd618", "", 1],
  ["xkcd", "pastel red", "#db5856"],
  ["xkcd", "greenish turquoise", "#00fbb0"],
  ["xkcd", "dark", "#1b2431"],
  ["xkcd", "ruby", "#ca0147"],
  ["xkcd", "poop green", "#6f7c00", "", 1],
  ["xkcd", "orangered", "#fe420f"],
  ["xkcd", "dandelion", "#fedf08"],
  ["xkcd", "claret", "#680018"],
  ["xkcd", "pale mauve", "#fed0fc"],
  ["xkcd", "lipstick", "#d5174e"],
  ["xkcd", "rosa", "#fe86a4"],
  ["xkcd", "darkblue", "#030764"],
  ["xkcd", "tan brown", "#ab7e4c"],
  ["xkcd", "shit green", "#758000", "", 1],
  ["xkcd", "red wine", "#8c0034"],
  ["xkcd", "pinky", "#fc86aa"],
  ["xkcd", "mud green", "#606602"],
  ["xkcd", "light greenish blue", "#63f7b4"],
  ["xkcd", "dull teal", "#5f9e8f"],
  ["xkcd", "deep lavender", "#8d5eb7"],
  ["xkcd", "vivid blue", "#152eff"],
  ["xkcd", "raw umber", "#a75e09"],
  ["xkcd", "light mint", "#b6ffbb"],
  ["xkcd", "light light blue", "#cafffb"],
  ["xkcd", "highlighter green", "#1bfc06"],
  ["xkcd", "greeny grey", "#7ea07a"],
  ["xkcd", "bluey grey", "#89a0b0"],
  ["xkcd", "algae", "#54ac68"],
  ["xkcd", "sap green", "#5c8b15"],
  ["xkcd", "pale salmon", "#ffb19a"],
  ["xkcd", "metallic blue", "#4f738e"],
  ["xkcd", "ice", "#d6fffa"],
  ["xkcd", "gross green", "#a0bf16"],
  ["xkcd", "dodger blue", "#3e82fc"],
  ["xkcd", "warm pink", "#fb5581"],
  ["xkcd", "light green blue", "#56fca2"],
  ["xkcd", "flat green", "#699d4c"],
  ["xkcd", "dark blue grey", "#1f3b4d"],
  ["xkcd", "clay brown", "#b2713d"],
  ["xkcd", "sand yellow", "#fce166"],
  ["xkcd", "grapefruit", "#fd5956"],
  ["xkcd", "blood orange", "#fe4b03"],
  ["xkcd", "very pale blue", "#d6fffe"],
  ["xkcd", "old pink", "#c77986"],
  ["xkcd", "neon red", "#ff073a"],
  ["xkcd", "golden rod", "#f9bc08"],
  ["xkcd", "plum purple", "#4e0550"],
  ["xkcd", "pale peach", "#ffe5ad"],
  ["xkcd", "dark yellow green", "#728f02"],
  ["xkcd", "carmine", "#9d0216"],
  ["xkcd", "deep sea blue", "#015482"],
  ["xkcd", "dark hot pink", "#d90166"],
  ["xkcd", "warm blue", "#4b57db"],
  ["xkcd", "light khaki", "#e6f2a2"],
  ["xkcd", "icky green", "#8fae22"],
  ["xkcd", "greenblue", "#23c48b"],
  ["xkcd", "dirty purple", "#734a65"],
  ["xkcd", "rich blue", "#021bf9"],
  ["xkcd", "mushroom", "#ba9e88"],
  ["xkcd", "flat blue", "#3c73a8"],
  ["xkcd", "dark slate blue", "#214761"],
  ["xkcd", "dark sage", "#598556"],
  ["xkcd", "coral pink", "#ff6163"],
  ["xkcd", "true green", "#089404"],
  ["xkcd", "darkish purple", "#751973"],
  ["xkcd", "dark taupe", "#7f684e"],
  ["xkcd", "cool grey", "#95a3a6"],
  ["xkcd", "canary", "#fdff63"],
  ["xkcd", "booger green", "#96b403", "", 1],
  ["xkcd", "muted pink", "#d1768f"],
  ["xkcd", "hazel", "#8e7618"],
  ["xkcd", "dark royal blue", "#02066f"],
  ["xkcd", "vivid purple", "#9900fa"],
  ["xkcd", "racing green", "#014600"],
  ["xkcd", "leather", "#ac7434"],
  ["xkcd", "green/blue", "#01c08d"],
  ["xkcd", "sunflower yellow", "#ffda03"],
  ["xkcd", "rich purple", "#720058"],
  ["xkcd", "pale magenta", "#d767ad"],
  ["xkcd", "light yellowish green", "#c2ff89"],
  ["xkcd", "indigo blue", "#3a18b1"],
  ["xkcd", "dark fuchsia", "#9d0759"],
  ["xkcd", "yellow tan", "#ffe36e"],
  ["xkcd", "wintergreen", "#20f986"],
  ["xkcd", "violet pink", "#fb5ffc"],
  ["xkcd", "topaz", "#13bbaf"],
  ["xkcd", "seafoam blue", "#78d1b6"],
  ["xkcd", "light gold", "#fddc5c"],
  ["xkcd", "grey/green", "#86a17d"],
  ["xkcd", "foam green", "#90fda9"],
  ["xkcd", "creme", "#ffffb6"],
  ["xkcd", "clear blue", "#247afd"],
  ["xkcd", "ugly blue", "#31668a", "", 1],
  ["xkcd", "terracota", "#cb6843"],
  ["xkcd", "very dark brown", "#1d0200"],
  ["xkcd", "straw", "#fcf679"],
  ["xkcd", "parchment", "#fefcaf"],
  ["xkcd", "orangey yellow", "#fdb915"],
  ["xkcd", "greyish teal", "#719f91"],
  ["xkcd", "sapphire", "#2138ab"],
  ["xkcd", "nice blue", "#107ab0"],
  ["xkcd", "browny orange", "#ca6b02"],
  ["xkcd", "washed out green", "#bcf5a6"],
  ["xkcd", "tiffany blue", "#7bf2da"],
  ["xkcd", "light seafoam", "#a0febf"],
  ["xkcd", "light neon green", "#4efd54"],
  ["xkcd", "light bright green", "#53fe5c"],
  ["xkcd", "light bluish green", "#76fda8"],
  ["xkcd", "rosy pink", "#f6688e"],
  ["xkcd", "peachy pink", "#ff9a8a"],
  ["xkcd", "pale light green", "#b1fc99"],
  ["xkcd", "old rose", "#c87f89"],
  ["xkcd", "fern", "#63a950"],
  ["xkcd", "dusk blue", "#26538d"],
  ["xkcd", "camo", "#7f8f4e"],
  ["xkcd", "burnt siena", "#b75203"],
  ["xkcd", "tealish green", "#0cdc73"],
  ["xkcd", "swamp", "#698339"],
  ["xkcd", "sand brown", "#cba560"],
  ["xkcd", "rust brown", "#8b3103"],
  ["xkcd", "orangeish", "#fd8d49"],
  ["xkcd", "light royal blue", "#3a2efe"],
  ["xkcd", "cocoa", "#875f42"],
  ["xkcd", "baby purple", "#ca9bf7"],
  ["xkcd", "raw sienna", "#9a6200"],
  ["xkcd", "radioactive green", "#2cfa1f"],
  ["xkcd", "light pea green", "#c4fe82"],
  ["xkcd", "cinnamon", "#ac4f06"],
  ["xkcd", "squash", "#f2ab15"],
  ["xkcd", "charcoal grey", "#3c4142"],
  ["xkcd", "bright yellow green", "#9dff00"],
  ["xkcd", "baby puke green", "#b6c406", "", 1],
  ["xkcd", "poison green", "#40fd14"],
  ["xkcd", "light lavendar", "#efc0fe"],
  ["xkcd", "indian red", "#850e04"],
  ["xkcd", "dark cream", "#fff39a"],
  ["xkcd", "toupe", "#c7ac7d"],
  ["xkcd", "butterscotch", "#fdb147"],
  ["xkcd", "burple", "#6832e3"],
  ["xkcd", "tan green", "#a9be70"],
  ["xkcd", "sun yellow", "#ffdf22"],
  ["xkcd", "pale gold", "#fdde6c"],
  ["xkcd", "light light green", "#c8ffb0"],
  ["xkcd", "lichen", "#8fb67b"],
  ["xkcd", "green/yellow", "#b5ce08"],
  ["xkcd", "darkgreen", "#054907"],
  ["xkcd", "azul", "#1d5dec"],
  ["xkcd", "sunny yellow", "#fff917"],
  ["xkcd", "sickly yellow", "#d0e429"],
  ["xkcd", "kelley green", "#009337"],
  ["xkcd", "bruise", "#7e4071"],
  ["xkcd", "browny green", "#6f6c0a"],
  ["xkcd", "battleship grey", "#6b7c85"],
  ["xkcd", "off blue", "#5684ae"],
  ["xkcd", "manilla", "#fffa86"],
  ["xkcd", "greenish beige", "#c9d179"],
  ["xkcd", "deep brown", "#410200"],
  ["xkcd", "darkish pink", "#da467d"],
  ["xkcd", "custard", "#fffd78"],
  ["xkcd", "ugly brown", "#7d7103", "", 1],
  ["xkcd", "stormy blue", "#507b9c"],
  ["xkcd", "liliac", "#c48efd"],
  ["xkcd", "baby shit brown", "#ad900d", "", 1],
  ["xkcd", "reddish grey", "#997570"],
  ["xkcd", "powder pink", "#ffb2d0"],
  ["xkcd", "eggplant purple", "#430541"],
  ["xkcd", "egg shell", "#fffcc4"],
  ["xkcd", "very light brown", "#d3b683"],
  ["xkcd", "tea green", "#bdf8a3"],
  ["xkcd", "orange pink", "#ff6f52"],
  ["xkcd", "light grey green", "#b7e1a1"],
  ["xkcd", "kiwi green", "#8ee53f"],
  ["xkcd", "boring green", "#63b365"],
  ["xkcd", "light pastel green", "#b2fba5"],
  ["xkcd", "candy pink", "#ff63e9"],
  ["xkcd", "purply", "#983fb2"],
  ["xkcd", "purpley grey", "#947e94"],
  ["xkcd", "dusty lavender", "#ac86a8"],
  ["xkcd", "desert", "#ccad60"],
  ["xkcd", "deep lilac", "#966ebd"],
  ["xkcd", "pig pink", "#e78ea5"],
  ["xkcd", "olive yellow", "#c2b709"],
  ["xkcd", "light seafoam green", "#a7ffb5"],
  ["xkcd", "light moss green", "#a6c875"],
  ["xkcd", "lavender pink", "#dd85d7"],
  ["xkcd", "deep aqua", "#08787f"],
  ["xkcd", "bland", "#afa88b"],
  ["xkcd", "strong pink", "#ff0789"],
  ["xkcd", "green teal", "#0cb577"],
  ["xkcd", "deep turquoise", "#017374"],
  ["xkcd", "dark green blue", "#1f6357"],
  ["xkcd", "bright sea green", "#05ffa6"],
  ["xkcd", "booger", "#9bb53c", "", 1],
  ["xkcd", "blue with a hint of purple", "#533cc6"],
  ["xkcd", "blue blue", "#2242c7"],
  ["xkcd", "windows blue", "#3778bf"],
  ["xkcd", "toxic green", "#61de2a"],
  ["xkcd", "strong blue", "#0c06f7"],
  ["xkcd", "spruce", "#0a5f38"],
  ["xkcd", "pinkish tan", "#d99b82"],
  ["xkcd", "macaroni and cheese", "#efb435"],
  ["xkcd", "grey teal", "#5e9b8a"],
  ["xkcd", "dusty teal", "#4c9085"],
  ["xkcd", "dark grass green", "#388004"],
  ["xkcd", "cement", "#a5a391"],
  ["xkcd", "yellowish tan", "#fcfc81"],
  ["xkcd", "warm purple", "#952e8f"],
  ["xkcd", "tea", "#65ab7c"],
  ["xkcd", "really light blue", "#d4ffff"],
  ["xkcd", "nasty green", "#70b23f"],
  ["xkcd", "light eggplant", "#894585"],
  ["xkcd", "fresh green", "#69d84f"],
  ["xkcd", "electric lime", "#a8ff04"],
  ["xkcd", "dust", "#b2996e"],
  ["xkcd", "dark pastel green", "#56ae57"],
  ["xkcd", "cloudy blue", "#acc2d9"],
  ["zh-trad", "乳白", "#f9f4dc", "rubai"],
  ["zh-trad", "杏仁黄", "#f7e8aa", "xingrenhuang"],
  ["zh-trad", "茉莉黄", "#f8df72", "molihuang"],
  ["zh-trad", "麦秆黄", "#f8df70", "maiganhuang"],
  ["zh-trad", "油菜花黄", "#fbda41", "youcaihuahuang"],
  ["zh-trad", "佛手黄", "#fed71a", "foshouhuang"],
  ["zh-trad", "篾黄", "#f7de98", "miehuang"],
  ["zh-trad", "葵扇黄", "#f8d86a", "kuishanhuang"],
  ["zh-trad", "柠檬黄", "#fcd337", "ningmenghuang"],
  ["zh-trad", "金瓜黄", "#fcd217", "jinguahuang"],
  ["zh-trad", "藤黄", "#ffd111", "tenghuang"],
  ["zh-trad", "酪黄", "#f6dead", "laohuang"],
  ["zh-trad", "香水玫瑰黄", "#f7da94", "xiangshuimeiguihuang"],
  ["zh-trad", "淡密黄", "#f9d367", "danmihuang"],
  ["zh-trad", "大豆黄", "#fbcd31", "dadouhuang"],
  ["zh-trad", "素馨黄", "#fccb16", "suxinhuang"],
  ["zh-trad", "向日葵黄", "#fecc11", "xiangrikuihuang"],
  ["zh-trad", "雅梨黄", "#fbc82f", "yalihuang"],
  ["zh-trad", "黄连黄", "#fcc515", "huanglianhuang"],
  ["zh-trad", "金盏黄", "#fcc307", "jinzhanhuang"],
  ["zh-trad", "蛋壳黄", "#f8c387", "dankehuang"],
  ["zh-trad", "肉色", "#f7c173", "rouse"],
  ["zh-trad", "鹅掌黄", "#fbb929", "ezhanghuang"],
  ["zh-trad", "鸡蛋黄", "#fbb612", "jidanhuang"],
  ["zh-trad", "鼬黄", "#fcb70a", "youhuang"],
  ["zh-trad", "榴萼黄", "#f9a633", "liuehuang"],
  ["zh-trad", "淡橘橙", "#fba414", "danjucheng"],
  ["zh-trad", "枇杷黄", "#fca106", "pipahuang"],
  ["zh-trad", "橙皮黄", "#fca104", "chengpihuang"],
  ["zh-trad", "北瓜黄", "#fc8c23", "beiguahuang"],
  ["zh-trad", "杏黄", "#f28e16", "xinghuang"],
  ["zh-trad", "雄黄", "#ff9900", "xionghuang"],
  ["zh-trad", "万寿菊黄", "#fb8b05", "wanshoujuhuang"],
  ["zh-trad", "菊蕾白", "#e9ddb6", "juleibai"],
  ["zh-trad", "秋葵黄", "#eed045", "qiukuihuang"],
  ["zh-trad", "硫华黄", "#f2ce2b", "liuhuahuang"],
  ["zh-trad", "柚黄", "#f1ca17", "youhuang"],
  ["zh-trad", "芒果黄", "#ddc871", "mangguohuang"],
  ["zh-trad", "蒿黄", "#dfc243", "haohuang"],
  ["zh-trad", "姜黄", "#e2c027", "jianghuang"],
  ["zh-trad", "香蕉黄", "#e4bf11", "xiangjiaohuang"],
  ["zh-trad", "草黄", "#d2b42c", "caohuang"],
  ["zh-trad", "新禾绿", "#d2b116", "xinhelv"],
  ["zh-trad", "月灰", "#b7ae8f", "yuehui"],
  ["zh-trad", "淡灰绿", "#ad9e5f", "danhuilv"],
  ["zh-trad", "草灰绿", "#8e804b", "caohuilv"],
  ["zh-trad", "苔绿", "#887322", "tailv"],
  ["zh-trad", "碧螺春绿", "#867018", "biluochunlv"],
  ["zh-trad", "燕羽灰", "#685e48", "yanyuhui"],
  ["zh-trad", "蟹壳灰", "#695e45", "xiekehui"],
  ["zh-trad", "潭水绿", "#645822", "tanshuilv"],
  ["zh-trad", "橄榄绿", "#5e5314", "ganlanlv"],
  ["zh-trad", "蚌肉白", "#f9f1db", "bangroubai"],
  ["zh-trad", "豆汁黄", "#f8e8c1", "douzhihuang"],
  ["zh-trad", "淡茧黄", "#f9d770", "danjianhuang"],
  ["zh-trad", "乳鸭黄", "#ffc90c", "ruyahuang"],
  ["zh-trad", "荔肉白", "#f2e6ce", "liroubai"],
  ["zh-trad", "象牙黄", "#f0d695", "xiangyahuang"],
  ["zh-trad", "炒米黄", "#f4ce69", "chaomihuang"],
  ["zh-trad", "鹦鹉冠黄", "#f6c430", "yingwuguanhuang"],
  ["zh-trad", "木瓜黄", "#f9c116", "muguahuang"],
  ["zh-trad", "浅烙黄", "#f9bd10", "qianlaohuang"],
  ["zh-trad", "莲子白", "#e5d3aa", "lianzibai"],
  ["zh-trad", "谷黄", "#e8b004", "guhuang"],
  ["zh-trad", "栀子黄", "#ebb10d", "zhizihuang"],
  ["zh-trad", "芥黄", "#d9a40e", "jiehuang"],
  ["zh-trad", "银鼠灰", "#b5aa90", "yinshuhui"],
  ["zh-trad", "尘灰", "#b6a476", "chenhui"],
  ["zh-trad", "枯绿", "#b78d12", "kulv"],
  ["zh-trad", "鲛青", "#87723e", "jiaoqing"],
  ["zh-trad", "粽叶绿", "#876818", "zongyelv"],
  ["zh-trad", "灰绿", "#8a6913", "huilv"],
  ["zh-trad", "鹤灰", "#4a4035", "hehui"],
  ["zh-trad", "淡松烟", "#4d4030", "dansongyan"],
  ["zh-trad", "暗海水绿", "#584717", "anhaishuilv"],
  ["zh-trad", "棕榈绿", "#5b4913", "zonglvlv"],
  ["zh-trad", "米色", "#f9e9cd", "mise"],
  ["zh-trad", "淡肉色", "#f8e0b0", "danrouse"],
  ["zh-trad", "麦芽糖黄", "#f9d27d", "maiyatanghuang"],
  ["zh-trad", "琥珀黄", "#feba07", "hupohuang"],
  ["zh-trad", "甘草黄", "#f3bf4c", "gancaohuang"],
  ["zh-trad", "初熟杏黄", "#f8bc31", "chushuxinghuang"],
  ["zh-trad", "浅驼色", "#e2c17c", "qiantuose"],
  ["zh-trad", "沙石黄", "#e5b751", "shashihuang"],
  ["zh-trad", "虎皮黄", "#eaad1a", "hupihuang"],
  ["zh-trad", "土黄", "#d6a01d", "tuhuang"],
  ["zh-trad", "百灵鸟灰", "#b4a992", "bailingniaohui"],
  ["zh-trad", "山鸡黄", "#b78b26", "shanjihuang"],
  ["zh-trad", "龟背黄", "#826b48", "guibeihuang"],
  ["zh-trad", "苍黄", "#806332", "canghuang"],
  ["zh-trad", "莱阳梨黄", "#815f25", "laiyanglihuang"],
  ["zh-trad", "蜴蜊绿", "#835e1d", "yililv"],
  ["zh-trad", "松鼠灰", "#4f4032", "songshuhui"],
  ["zh-trad", "橄榄灰", "#503e2a", "ganlanhui"],
  ["zh-trad", "蟹壳绿", "#513c20", "xiekelv"],
  ["zh-trad", "古铜绿", "#533c1b", "gutonglv"],
  ["zh-trad", "焦茶绿", "#553b18", "jiaochalv"],
  ["zh-trad", "粉白", "#fbf2e3", "fenbai"],
  ["zh-trad", "落英淡粉", "#f9e8d0", "luoyingdanfen"],
  ["zh-trad", "瓜瓤粉", "#f9cb8b", "guarangfen"],
  ["zh-trad", "蜜黄", "#fbb957", "mihuang"],
  ["zh-trad", "金叶黄", "#ffa60f", "jinyehuang"],
  ["zh-trad", "金莺黄", "#f4a83a", "jinyinghuang"],
  ["zh-trad", "鹿角棕", "#e3bd8d", "lujiaozong"],
  ["zh-trad", "凋叶棕", "#e7a23f", "diaoyezong"],
  ["zh-trad", "玳瑁黄", "#daa45a", "daimaohuang"],
  ["zh-trad", "软木黄", "#de9e44", "ruanmuhuang"],
  ["zh-trad", "风帆黄", "#dc9123", "fengfanhuang"],
  ["zh-trad", "桂皮淡棕", "#c09351", "guipidanzong"],
  ["zh-trad", "猴毛灰", "#97846c", "houmaohui"],
  ["zh-trad", "山鸡褐", "#986524", "shanjihe"],
  ["zh-trad", "驼色", "#66462a", "tuose"],
  ["zh-trad", "茶褐", "#5d3d21", "chahe"],
  ["zh-trad", "古铜褐", "#5c3719", "gutonghe"],
  ["zh-trad", "荷花白", "#fbecde", "hehuabai"],
  ["zh-trad", "玫瑰粉", "#f8b37f", "meiguifen"],
  ["zh-trad", "橘橙", "#f97d1c", "jucheng"],
  ["zh-trad", "美人焦橙", "#fa7e23", "meirenjiaocheng"],
  ["zh-trad", "润红", "#f7cdbc", "runhong"],
  ["zh-trad", "淡桃红", "#f6cec1", "dantaohong"],
  ["zh-trad", "海螺橙", "#f0945d", "hailuocheng"],
  ["zh-trad", "桃红", "#f0ada0", "taohong"],
  ["zh-trad", "颊红", "#eeaa9c", "jiahong"],
  ["zh-trad", "淡罂粟红", "#eea08c", "danyingsuhong"],
  ["zh-trad", "晨曦红", "#ea8958", "chenxihong"],
  ["zh-trad", "蟹壳红", "#f27635", "xiekehong"],
  ["zh-trad", "金莲花橙", "#f86b1d", "jinlianhuacheng"],
  ["zh-trad", "草莓红", "#ef6f48", "caomeihong"],
  ["zh-trad", "龙睛鱼红", "#ef632b", "longjingyuhong"],
  ["zh-trad", "蜻蜓红", "#f1441d", "qingtinghong"],
  ["zh-trad", "大红", "#f04b22", "dahong"],
  ["zh-trad", "柿红", "#f2481b", "shihong"],
  ["zh-trad", "榴花红", "#f34718", "liuhuahong"],
  ["zh-trad", "银朱", "#f43e06", "yinzhu"],
  ["zh-trad", "朱红", "#ed5126", "zhuhong"],
  ["zh-trad", "鲑鱼红", "#f09c5a", "guiyuhong"],
  ["zh-trad", "金黄", "#f26b1f", "jinhuang"],
  ["zh-trad", "鹿皮褐", "#d99156", "lupihe"],
  ["zh-trad", "醉瓜肉", "#db8540", "zuiguarou"],
  ["zh-trad", "麂棕", "#de7622", "jizong"],
  ["zh-trad", "淡银灰", "#c1b2a3", "danyinhui"],
  ["zh-trad", "淡赭", "#be7e4a", "danzhe"],
  ["zh-trad", "槟榔综", "#c1651a", "binglangzong"],
  ["zh-trad", "银灰", "#918072", "yinhui"],
  ["zh-trad", "海鸥灰", "#9a8878", "haiouhui"],
  ["zh-trad", "淡咖啡", "#945833", "dankafei"],
  ["zh-trad", "岩石棕", "#964d22", "yanshizong"],
  ["zh-trad", "芒果棕", "#954416", "mangguozong"],
  ["zh-trad", "石板灰", "#624941", "shibanhui"],
  ["zh-trad", "珠母灰", "#64483d", "zhumuhui"],
  ["zh-trad", "丁香棕", "#71361d", "dingxiangzong"],
  ["zh-trad", "咖啡", "#753117", "kafei"],
  ["zh-trad", "筍皮棕", "#732e12", "sunpizong"],
  ["zh-trad", "燕颔红", "#fc6315", "yanhanhong"],
  ["zh-trad", "玉粉红", "#e8b49a", "yufenhong"],
  ["zh-trad", "金驼", "#e46828", "jintuo"],
  ["zh-trad", "铁棕", "#d85916", "tiezong"],
  ["zh-trad", "蛛网灰", "#b7a091", "zhuwanghui"],
  ["zh-trad", "淡可可棕", "#b7511d", "dankekezong"],
  ["zh-trad", "中红灰", "#8b614d", "zhonghonghui"],
  ["zh-trad", "淡土黄", "#8c4b31", "dantuhuang"],
  ["zh-trad", "淡豆沙", "#873d24", "dandousha"],
  ["zh-trad", "椰壳棕", "#883a1e", "yekezong"],
  ["zh-trad", "淡铁灰", "#5b423a", "dantiehui"],
  ["zh-trad", "中灰驼", "#603d30", "zhonghuituo"],
  ["zh-trad", "淡栗棕", "#673424", "danlizong"],
  ["zh-trad", "可可棕", "#652b1c", "kekezong"],
  ["zh-trad", "柞叶棕", "#692a1b", "zhayezong"],
  ["zh-trad", "野蔷薇红", "#fb9968", "yeqiangweihong"],
  ["zh-trad", "菠萝红", "#fc7930", "boluohong"],
  ["zh-trad", "藕荷", "#edc3ae", "ouhe"],
  ["zh-trad", "陶瓷红", "#e16723", "taocihong"],
  ["zh-trad", "晓灰", "#d4c4b7", "xiaohui"],
  ["zh-trad", "余烬红", "#cf7543", "yujinhong"],
  ["zh-trad", "火砖红", "#cd6227", "huozhuanhong"],
  ["zh-trad", "火泥棕", "#aa6a4c", "huonizong"],
  ["zh-trad", "绀红", "#a6522c", "ganhong"],
  ["zh-trad", "橡树棕", "#773d31", "xiangshuzong"],
  ["zh-trad", "海报灰", "#483332", "haibaohui"],
  ["zh-trad", "玫瑰灰", "#4b2e2b", "meiguihui"],
  ["zh-trad", "火山棕", "#482522", "huoshanzong"],
  ["zh-trad", "豆沙", "#481e1c", "dousha"],
  ["zh-trad", "淡米粉", "#fbeee2", "danmifen"],
  ["zh-trad", "初桃粉红", "#f6dcce", "chutaofenhong"],
  ["zh-trad", "介壳淡粉红", "#f7cfba", "jieqiaodanfenhong"],
  ["zh-trad", "淡藏花红", "#f6ad8f", "dancanghuahong"],
  ["zh-trad", "瓜瓤红", "#f68c60", "guaranghong"],
  ["zh-trad", "芙蓉红", "#f9723d", "furonghong"],
  ["zh-trad", "莓酱红", "#fa5d19", "meijianghong"],
  ["zh-trad", "法螺红", "#ee8055", "faluohong"],
  ["zh-trad", "落霞红", "#cf4813", "luoxiahong"],
  ["zh-trad", "淡玫瑰灰", "#b89485", "danmeiguihui"],
  ["zh-trad", "蟹蝥红", "#b14b28", "xiemaohong"],
  ["zh-trad", "火岩棕", "#863020", "huoyanzong"],
  ["zh-trad", "赭石", "#862617", "zheshi"],
  ["zh-trad", "暗驼棕", "#592620", "antuozong"],
  ["zh-trad", "酱棕", "#5a1f1b", "jiangzong"],
  ["zh-trad", "栗棕", "#5c1e19", "lizong"],
  ["zh-trad", "洋水仙红", "#f4c7ba", "yangshuixianhong"],
  ["zh-trad", "谷鞘红", "#f17666", "guqiaohong"],
  ["zh-trad", "苹果红", "#f15642", "pingguohong"],
  ["zh-trad", "铁水红", "#f5391c", "tieshuihong"],
  ["zh-trad", "桂红", "#f25a47", "guihong"],
  ["zh-trad", "极光红", "#f33b1f", "jiguanghong"],
  ["zh-trad", "粉红", "#f2b9b2", "fenhong"],
  ["zh-trad", "舌红", "#f19790", "shehong"],
  ["zh-trad", "曲红", "#f05a46", "quhong"],
  ["zh-trad", "红汞红", "#f23e23", "honggonghong"],
  ["zh-trad", "淡绯", "#f2cac9", "danfei"],
  ["zh-trad", "无花果红", "#efafad", "wuhuaguohong"],
  ["zh-trad", "榴子红", "#f1908c", "liuzihong"],
  ["zh-trad", "胭脂红", "#f03f24", "yanzhihong"],
  ["zh-trad", "合欢红", "#f0a1a8", "hehuanhong"],
  ["zh-trad", "春梅红", "#f1939c", "chunmeihong"],
  ["zh-trad", "香叶红", "#f07c82", "xiangyehong"],
  ["zh-trad", "珊瑚红", "#f04a3a", "shanhuhong"],
  ["zh-trad", "萝卜红", "#f13c22", "luobohong"],
  ["zh-trad", "淡茜红", "#e77c8e", "danqianhong"],
  ["zh-trad", "艳红", "#ed5a65", "yanhong"],
  ["zh-trad", "淡菽红", "#ed4845", "danshuhong"],
  ["zh-trad", "鱼鳃红", "#ed3b2f", "yusaihong"],
  ["zh-trad", "樱桃红", "#ed3321", "yingtaohong"],
  ["zh-trad", "淡蕊香红", "#ee4866", "danruixianghong"],
  ["zh-trad", "石竹红", "#ee4863", "shizhuhong"],
  ["zh-trad", "草茉莉红", "#ef475d", "caomolihong"],
  ["zh-trad", "茶花红", "#ee3f4d", "chahuahong"],
  ["zh-trad", "枸枢红", "#ed3333", "goushuhong"],
  ["zh-trad", "秋海棠红", "#ec2b24", "qiuhaitanghong"],
  ["zh-trad", "丽春红", "#eb261a", "lichunhong"],
  ["zh-trad", "夕阳红", "#de2a18", "xiyanghong"],
  ["zh-trad", "鹤顶红", "#d42517", "hedinghong"],
  ["zh-trad", "鹅血石红", "#ab372f", "exueshihong"],
  ["zh-trad", "覆盆子红", "#ac1f18", "fupenzihong"],
  ["zh-trad", "貂紫", "#5d3131", "diaozi"],
  ["zh-trad", "暗玉紫", "#5c2223", "anyuzi"],
  ["zh-trad", "栗紫", "#5a191b", "lizi"],
  ["zh-trad", "葡萄酱紫", "#5a1216", "putaojiangzi"],
  ["zh-trad", "牡丹粉红", "#eea2a4", "mudanfenhong"],
  ["zh-trad", "山茶红", "#ed556a", "shanchahong"],
  ["zh-trad", "海棠红", "#f03752", "haitanghong"],
  ["zh-trad", "玉红", "#c04851", "yuhong"],
  ["zh-trad", "高粱红", "#c02c38", "gaolianghong"],
  ["zh-trad", "满江红", "#a7535a", "manjianghong"],
  ["zh-trad", "枣红", "#7c1823", "zaohong"],
  ["zh-trad", "葡萄紫", "#4c1f24", "putaozi"],
  ["zh-trad", "酱紫", "#4d1018", "jiangzi"],
  ["zh-trad", "淡曙红", "#ee2746", "danshuhong"],
  ["zh-trad", "唐菖蒲红", "#de1c31", "tangchangpuhong"],
  ["zh-trad", "鹅冠红", "#d11a2d", "eguanhong"],
  ["zh-trad", "莓红", "#c45a65", "meihong"],
  ["zh-trad", "枫叶红", "#c21f30", "fengyehong"],
  ["zh-trad", "苋菜红", "#a61b29", "xiancaihong"],
  ["zh-trad", "烟红", "#894e54", "yanhong"],
  ["zh-trad", "暗紫苑红", "#82202b", "anziyuanhong"],
  ["zh-trad", "殷红", "#82111f", "yanhong"],
  ["zh-trad", "猪肝紫", "#541e24", "zhuganzi"],
  ["zh-trad", "金鱼紫", "#500a16", "jinyuzi"],
  ["zh-trad", "草珠红", "#f8ebe6", "caozhuhong"],
  ["zh-trad", "淡绛红", "#ec7696", "danjianghong"],
  ["zh-trad", "品红", "#ef3473", "pinhong"],
  ["zh-trad", "凤仙花红", "#ea7293", "fengxianhuahong"],
  ["zh-trad", "粉团花红", "#ec9bad", "fentuanhuahong"],
  ["zh-trad", "夹竹桃红", "#eb507e", "jiazhutaohong"],
  ["zh-trad", "榲桲红", "#ed2f6a", "wenpohong"],
  ["zh-trad", "姜红", "#eeb8c3", "jianghong"],
  ["zh-trad", "莲瓣红", "#ea517f", "lianbanhong"],
  ["zh-trad", "水红", "#f1c4cd", "shuihong"],
  ["zh-trad", "报春红", "#ec8aa4", "baochunhong"],
  ["zh-trad", "月季红", "#ce5777", "yuejihong"],
  ["zh-trad", "豇豆红", "#ed9db2", "jiangdouhong"],
  ["zh-trad", "霞光红", "#ef82a0", "xiaguanghong"],
  ["zh-trad", "松叶牡丹红", "#eb3c70", "songyemudanhong"],
  ["zh-trad", "喜蛋红", "#ec2c64", "xidanhong"],
  ["zh-trad", "鼠鼻红", "#e3b4b8", "shubihong"],
  ["zh-trad", "尖晶玉红", "#cc163a", "jianjingyuhong"],
  ["zh-trad", "山黎豆红", "#c27c88", "shanlidouhong"],
  ["zh-trad", "锦葵红", "#bf3553", "jinkuihong"],
  ["zh-trad", "鼠背灰", "#73575c", "shubeihui"],
  ["zh-trad", "甘蔗紫", "#621624", "ganzhezi"],
  ["zh-trad", "石竹紫", "#63071c", "shizhuzi"],
  ["zh-trad", "苍蝇灰", "#36282b", "cangyinghui"],
  ["zh-trad", "卵石紫", "#30161c", "luanshizi"],
  ["zh-trad", "李紫", "#2b1216", "lizi"],
  ["zh-trad", "茄皮紫", "#2d0c13", "qiepizi"],
  ["zh-trad", "吊钟花红", "#ce5e8a", "diaozhonghuahong"],
  ["zh-trad", "兔眼红", "#ec4e8a", "tuyanhong"],
  ["zh-trad", "紫荆红", "#ee2c79", "zijinghong"],
  ["zh-trad", "菜头紫", "#951c48", "caitouzi"],
  ["zh-trad", "鹞冠紫", "#621d34", "yaoguanzi"],
  ["zh-trad", "葡萄酒红", "#62102e", "putaojiuhong"],
  ["zh-trad", "磨石紫", "#382129", "moshizi"],
  ["zh-trad", "檀紫", "#381924", "tanzi"],
  ["zh-trad", "火鹅紫", "#33141e", "huoezi"],
  ["zh-trad", "墨紫", "#310f1b", "mozi"],
  ["zh-trad", "晶红", "#eea6b7", "jinghong"],
  ["zh-trad", "扁豆花红", "#ef498b", "biandouhuahong"],
  ["zh-trad", "白芨红", "#de7897", "baijihong"],
  ["zh-trad", "嫩菱红", "#de3f7c", "nenlinghong"],
  ["zh-trad", "菠根红", "#d13c74", "bogenhong"],
  ["zh-trad", "酢酱草红", "#c5708b", "cujiangcaohong"],
  ["zh-trad", "洋葱紫", "#a8456b", "yangcongzi"],
  ["zh-trad", "海象紫", "#4b1e2f", "haixiangzi"],
  ["zh-trad", "绀紫", "#461629", "ganzi"],
  ["zh-trad", "古铜紫", "#440e25", "gutongzi"],
  ["zh-trad", "石蕊红", "#f0c9cf", "shiruihong"],
  ["zh-trad", "芍药耕红", "#eba0b3", "shaoyaogenghong"],
  ["zh-trad", "藏花红", "#ec2d7a", "canghuahong"],
  ["zh-trad", "初荷红", "#e16c96", "chuhehong"],
  ["zh-trad", "马鞭草紫", "#ede3e7", "mabiancaozi"],
  ["zh-trad", "丁香淡紫", "#e9d7df", "dingxiangdanzi"],
  ["zh-trad", "丹紫红", "#d2568c", "danzihong"],
  ["zh-trad", "玫瑰红", "#d2357d", "meiguihong"],
  ["zh-trad", "淡牵牛紫", "#d1c2d3", "danqianniuzi"],
  ["zh-trad", "凤信紫", "#c8adc4", "fengxinzi"],
  ["zh-trad", "萝兰紫", "#c08eaf", "luolanzi"],
  ["zh-trad", "玫瑰紫", "#ba2f7b", "meiguizi"],
  ["zh-trad", "藤萝紫", "#8076a3", "tengluozi"],
  ["zh-trad", "槿紫", "#806d9e", "jinzi"],
  ["zh-trad", "蕈紫", "#815c94", "xunzi"],
  ["zh-trad", "桔梗紫", "#813c85", "jiegengzi"],
  ["zh-trad", "魏紫", "#7e1671", "weizi"],
  ["zh-trad", "芝兰紫", "#e9ccd3", "zhilanzi"],
  ["zh-trad", "菱锰红", "#d276a3", "lingmenghong"],
  ["zh-trad", "龙须红", "#cc5595", "longxuhong"],
  ["zh-trad", "蓟粉红", "#e6d2d5", "jifenhong"],
  ["zh-trad", "电气石红", "#c35691", "dianqishihong"],
  ["zh-trad", "樱草紫", "#c06f98", "yingcaozi"],
  ["zh-trad", "芦穗灰", "#bdaead", "lusuihui"],
  ["zh-trad", "隐红灰", "#b598a1", "yinhonghui"],
  ["zh-trad", "苋菜紫", "#9b1e64", "xiancaizi"],
  ["zh-trad", "芦灰", "#856d72", "luhui"],
  ["zh-trad", "暮云灰", "#4f383e", "muyunhui"],
  ["zh-trad", "斑鸠灰", "#482936", "banjiuhui"],
  ["zh-trad", "淡藤萝紫", "#f2e7e5", "dantengluozi"],
  ["zh-trad", "淡青紫", "#e0c8d1", "danqingzi"],
  ["zh-trad", "青蛤壳紫", "#bc84a8", "qinghakezi"],
  ["zh-trad", "豆蔻紫", "#ad6598", "doukouzi"],
  ["zh-trad", "扁豆紫", "#a35c8f", "biandouzi"],
  ["zh-trad", "芥花紫", "#983680", "jiehuazi"],
  ["zh-trad", "青莲", "#8b2671", "qinglian"],
  ["zh-trad", "芓紫", "#894276", "zizi"],
  ["zh-trad", "葛巾紫", "#7e2065", "gejinzi"],
  ["zh-trad", "牵牛紫", "#681752", "qianniuzi"],
  ["zh-trad", "紫灰", "#5d3f51", "zihui"],
  ["zh-trad", "龙睛鱼紫", "#4e2a40", "longjingyuzi"],
  ["zh-trad", "荸荠紫", "#411c35", "biqizi"],
  ["zh-trad", "古鼎灰", "#36292f", "gudinghui"],
  ["zh-trad", "乌梅紫", "#1e131d", "wumeizi"],
  ["zh-trad", "深牵牛紫", "#1c0d1a", "shenqianniuzi"],
  ["zh-trad", "银白", "#f1f0ed", "yinbai"],
  ["zh-trad", "芡食白", "#e2e1e4", "qianshibai"],
  ["zh-trad", "远山紫", "#ccccd6", "yuanshanzi"],
  ["zh-trad", "淡蓝紫", "#a7a8bd", "danlanzi"],
  ["zh-trad", "山梗紫", "#61649f", "shangengzi"],
  ["zh-trad", "螺甸紫", "#74759b", "luodianzi"],
  ["zh-trad", "玛瑙灰", "#cfccc9", "manaohui"],
  ["zh-trad", "野菊紫", "#525288", "yejuzi"],
  ["zh-trad", "满天星紫", "#2e317c", "mantianxingzi"],
  ["zh-trad", "锌灰", "#7a7374", "xinhui"],
  ["zh-trad", "野葡萄紫", "#302f4b", "yeputaozi"],
  ["zh-trad", "剑锋紫", "#3e3841", "jianfengzi"],
  ["zh-trad", "龙葵紫", "#322f3b", "longkuizi"],
  ["zh-trad", "暗龙胆紫", "#22202e", "anlongdanzi"],
  ["zh-trad", "晶石紫", "#1f2040", "jingshizi"],
  ["zh-trad", "暗蓝紫", "#131124", "anlanzi"],
  ["zh-trad", "景泰蓝", "#2775b6", "jingtailan"],
  ["zh-trad", "尼罗蓝", "#2474b5", "niluolan"],
  ["zh-trad", "远天蓝", "#d0dfe6", "yuantianlan"],
  ["zh-trad", "星蓝", "#93b5cf", "xinglan"],
  ["zh-trad", "羽扇豆蓝", "#619ac3", "yushandoulan"],
  ["zh-trad", "花青", "#2376b7", "huaqing"],
  ["zh-trad", "睛蓝", "#5698c3", "jinglan"],
  ["zh-trad", "虹蓝", "#2177b8", "honglan"],
  ["zh-trad", "湖水蓝", "#b0d5df", "hushuilan"],
  ["zh-trad", "秋波蓝", "#8abcd1", "qiubolan"],
  ["zh-trad", "涧石蓝", "#66a9c9", "jianshilan"],
  ["zh-trad", "潮蓝", "#2983bb", "chaolan"],
  ["zh-trad", "群青", "#1772b4", "qunqing"],
  ["zh-trad", "霁青", "#63bbd0", "jiqing"],
  ["zh-trad", "碧青", "#5cb3cc", "biqing"],
  ["zh-trad", "宝石蓝", "#2486b9", "baoshilan"],
  ["zh-trad", "天蓝", "#1677b3", "tianlan"],
  ["zh-trad", "柏林蓝", "#126bae", "bolinlan"],
  ["zh-trad", "海青", "#22a2c3", "haiqing"],
  ["zh-trad", "钴蓝", "#1a94bc", "gulan"],
  ["zh-trad", "鸢尾蓝", "#158bb8", "yuanweilan"],
  ["zh-trad", "牵牛花蓝", "#1177b0", "qianniuhualan"],
  ["zh-trad", "飞燕草蓝", "#0f59a4", "feiyancaolan"],
  ["zh-trad", "品蓝", "#2b73af", "pinlan"],
  ["zh-trad", "银鱼白", "#cdd1d3", "yinyubai"],
  ["zh-trad", "安安蓝", "#3170a7", "ananlan"],
  ["zh-trad", "鱼尾灰", "#5e616d", "yuweihui"],
  ["zh-trad", "鲸鱼灰", "#475164", "jingyuhui"],
  ["zh-trad", "海参灰", "#fffefa", "haishenhui"],
  ["zh-trad", "沙鱼灰", "#35333c", "shayuhui"],
  ["zh-trad", "钢蓝", "#0f1423", "ganglan"],
  ["zh-trad", "云水蓝", "#baccd9", "yunshuilan"],
  ["zh-trad", "晴山蓝", "#8fb2c9", "qingshanlan"],
  ["zh-trad", "靛青", "#1661ab", "dianqing"],
  ["zh-trad", "大理石灰", "#c4cbcf", "dalishihui"],
  ["zh-trad", "海涛蓝", "#15559a", "haitaolan"],
  ["zh-trad", "蝶翅蓝", "#4e7ca1", "diechilan"],
  ["zh-trad", "海军蓝", "#346c9c", "haijunlan"],
  ["zh-trad", "水牛灰", "#2f2f35", "shuiniuhui"],
  ["zh-trad", "牛角灰", "#2d2e36", "niujiaohui"],
  ["zh-trad", "燕颔蓝", "#131824", "yanhanlan"],
  ["zh-trad", "云峰白", "#d8e3e7", "yunfengbai"],
  ["zh-trad", "井天蓝", "#c3d7df", "jingtianlan"],
  ["zh-trad", "云山蓝", "#2f90b9", "yunshanlan"],
  ["zh-trad", "釉蓝", "#1781b5", "youlan"],
  ["zh-trad", "鸥蓝", "#c7d2d4", "oulan"],
  ["zh-trad", "搪磁蓝", "#11659a", "tangcilan"],
  ["zh-trad", "月影白", "#c0c4c3", "yueyingbai"],
  ["zh-trad", "星灰", "#b2bbbe", "xinghui"],
  ["zh-trad", "淡蓝灰", "#5e7987", "danlanhui"],
  ["zh-trad", "鷃蓝", "#144a74", "yanlan"],
  ["zh-trad", "嫩灰", "#74787a", "nenhui"],
  ["zh-trad", "战舰灰", "#495c69", "zhanjianhui"],
  ["zh-trad", "瓦罐灰", "#47484c", "waguanhui"],
  ["zh-trad", "青灰", "#2b333e", "qinghui"],
  ["zh-trad", "鸽蓝", "#1c2938", "gelan"],
  ["zh-trad", "钢青", "#142334", "gangqing"],
  ["zh-trad", "暗蓝", "#101f30", "anlan"],
  ["zh-trad", "月白", "#eef7f2", "yuebai"],
  ["zh-trad", "海天蓝", "#c6e6e8", "haitianlan"],
  ["zh-trad", "清水蓝", "#93d5dc", "qingshuilan"],
  ["zh-trad", "瀑布蓝", "#51c4d3", "pubulan"],
  ["zh-trad", "蔚蓝", "#29b7cb", "weilan"],
  ["zh-trad", "孔雀蓝", "#0eb0c9", "kongquelan"],
  ["zh-trad", "甸子蓝", "#10aec2", "dianzilan"],
  ["zh-trad", "石绿", "#57c3c2", "shilv"],
  ["zh-trad", "竹篁绿", "#b9dec9", "zhuhuanglv"],
  ["zh-trad", "粉绿", "#83cbac", "fenlv"],
  ["zh-trad", "美蝶绿", "#12aa9c", "meidielv"],
  ["zh-trad", "毛绿", "#66c18c", "maolv"],
  ["zh-trad", "蔻梢绿", "#5dbe8a", "koushaolv"],
  ["zh-trad", "麦苗绿", "#55bb8a", "maimiaolv"],
  ["zh-trad", "蛙绿", "#45b787", "walv"],
  ["zh-trad", "铜绿", "#2bae85", "tonglv"],
  ["zh-trad", "竹绿", "#1ba784", "zhulv"],
  ["zh-trad", "蓝绿", "#12a182", "lanlv"],
  ["zh-trad", "穹灰", "#c4d7d6", "qionghui"],
  ["zh-trad", "翠蓝", "#1e9eb3", "cuilan"],
  ["zh-trad", "胆矾蓝", "#0f95b0", "danfanlan"],
  ["zh-trad", "樫鸟蓝", "#1491a8", "jianniaolan"],
  ["zh-trad", "闪蓝", "#7cabb1", "shanlan"],
  ["zh-trad", "冰山蓝", "#a4aca7", "bingshanlan"],
  ["zh-trad", "虾壳青", "#869d9d", "xiakeqing"],
  ["zh-trad", "晚波蓝", "#648e93", "wanbolan"],
  ["zh-trad", "蜻蜓蓝", "#3b818c", "qingtinglan"],
  ["zh-trad", "玉鈫蓝", "#126e82", "yuqinlan"],
  ["zh-trad", "垩灰", "#737c7b", "ehui"],
  ["zh-trad", "夏云灰", "#617172", "xiayunhui"],
  ["zh-trad", "苍蓝", "#134857", "canglan"],
  ["zh-trad", "黄昏灰", "#474b4c", "huanghunhui"],
  ["zh-trad", "灰蓝", "#21373d", "huilan"],
  ["zh-trad", "深灰蓝", "#132c33", "shenhuilan"],
  ["zh-trad", "玉簪绿", "#a4cab6", "yuzanlv"],
  ["zh-trad", "青矾绿", "#2c9678", "qingfanlv"],
  ["zh-trad", "草原远绿", "#9abeaf", "caoyuanyuanlv"],
  ["zh-trad", "梧枝绿", "#69a794", "wuzhilv"],
  ["zh-trad", "浪花绿", "#92b3a5", "langhualv"],
  ["zh-trad", "海王绿", "#248067", "haiwanglv"],
  ["zh-trad", "亚丁绿", "#428675", "yadinglv"],
  ["zh-trad", "镍灰", "#9fa39a", "niehui"],
  ["zh-trad", "明灰", "#8a988e", "minghui"],
  ["zh-trad", "淡绿灰", "#70887d", "danlvhui"],
  ["zh-trad", "飞泉绿", "#497568", "feiquanlv"],
  ["zh-trad", "狼烟灰", "#5d655f", "langyanhui"],
  ["zh-trad", "绿灰", "#314a43", "lvhui"],
  ["zh-trad", "苍绿", "#223e36", "canglv"],
  ["zh-trad", "深海绿", "#1a3b32", "shenhailv"],
  ["zh-trad", "长石灰", "#363433", "changshihui"],
  ["zh-trad", "苷蓝绿", "#1f2623", "ganlanlv"],
  ["zh-trad", "莽丛绿", "#141e1b", "mangconglv"],
  ["zh-trad", "淡翠绿", "#c6dfc8", "dancuilv"],
  ["zh-trad", "明绿", "#9eccab", "minglv"],
  ["zh-trad", "田园绿", "#68b88e", "tianyuanlv"],
  ["zh-trad", "翠绿", "#20a162", "cuilv"],
  ["zh-trad", "淡绿", "#61ac85", "danlv"],
  ["zh-trad", "葱绿", "#40a070", "conglv"],
  ["zh-trad", "孔雀绿", "#229453", "kongquelv"],
  ["zh-trad", "艾绿", "#cad3c3", "ailv"],
  ["zh-trad", "蟾绿", "#3c9566", "chanlv"],
  ["zh-trad", "宫殿绿", "#20894d", "gongdianlv"],
  ["zh-trad", "松霜绿", "#83a78d", "songshuanglv"],
  ["zh-trad", "蛋白石绿", "#579572", "danbaishilv"],
  ["zh-trad", "薄荷绿", "#207f4c", "bohelv"],
  ["zh-trad", "瓦松绿", "#6e8b74", "wasonglv"],
  ["zh-trad", "荷叶绿", "#1a6840", "heyelv"],
  ["zh-trad", "田螺绿", "#5e665b", "tianluolv"],
  ["zh-trad", "白屈菜绿", "#485b4d", "baiqucailv"],
  ["zh-trad", "河豚灰", "#393733", "hetunhui"],
  ["zh-trad", "蒽油绿", "#373834", "enyoulv"],
  ["zh-trad", "槲寄生绿", "#2b312c", "hujishenglv"],
  ["zh-trad", "云杉绿", "#15231b", "yunshanlv"],
  ["zh-trad", "嫩菊绿", "#f0f5e5", "nenjulv"],
  ["zh-trad", "艾背绿", "#dfecd5", "aibeilv"],
  ["zh-trad", "嘉陵水绿", "#add5a2", "jialingshuilv"],
  ["zh-trad", "玉髓绿", "#41b349", "yusuilv"],
  ["zh-trad", "鲜绿", "#43b244", "xianlv"],
  ["zh-trad", "宝石绿", "#41ae3c", "baoshilv"],
  ["zh-trad", "海沫绿", "#e2e7bf", "haimolyu"],
  ["zh-trad", "姚黄", "#d0deaa", "yaohuang"],
  ["zh-trad", "橄榄石绿", "#b2cf87", "ganlanshilv"],
  ["zh-trad", "水绿", "#8cc269", "shuilv"],
  ["zh-trad", "芦苇绿", "#b7d07a", "luweilv"],
  ["zh-trad", "槐花黄绿", "#d2d97a", "huaihuahuanglv"],
  ["zh-trad", "苹果绿", "#bacf65", "pingguolv"],
  ["zh-trad", "芽绿", "#96c24e", "yalv"],
  ["zh-trad", "蝶黄", "#e2d849", "diehuang"],
  ["zh-trad", "橄榄黄绿", "#bec936", "ganlanhuanglv"],
  ["zh-trad", "鹦鹉绿", "#5bae23", "yingwulv"],
  ["zh-trad", "油绿", "#253d24", "youlv"],
  ["zh-trad", "象牙白", "#fffef8", "xiangyabai"],
  ["zh-trad", "汉白玉", "#f8f4ed", "hanbaiyu"],
  ["zh-trad", "雪白", "#fffef9", "xuebai"],
  ["zh-trad", "鱼肚白", "#f7f4ed", "yudubai"],
  ["zh-trad", "珍珠灰", "#e4dfd7", "zhenzhuhui"],
  ["zh-trad", "浅灰", "#dad4cb", "qianhui"],
  ["zh-trad", "铅灰", "#bbb5ac", "qianhui"],
  ["zh-trad", "中灰", "#a49c93", "zhonghui"],
  ["zh-trad", "瓦灰", "#867e76", "wahui"],
  ["zh-trad", "夜灰", "#847c74", "yehui"],
  ["zh-trad", "雁灰", "#80766e", "yanhui"],
  ["zh-trad", "深灰", "#81776e", "shenhui"],
  ["ja-trad", "桜色", "#fef4f4", "さくらいろ"],
  ["ja-trad", "小豆色", "#96514d", "あずきいろ"],
  ["ja-trad", "黄金", "#e6b422", "こがね"],
  ["ja-trad", "萌葱色", "#006e54", "もえぎいろ"],
  ["ja-trad", "古代紫", "#895b8a", "こだいむらさき"],
  ["ja-trad", "薄桜", "#fdeff2", "うすざくら"],
  ["ja-trad", "枯茶", "#8d6449", "からちゃ"],
  ["ja-trad", "櫨染", "#d9a62e", "はじぞめ"],
  ["ja-trad", "花緑青", "#00a381", "はなろくしょう"],
  ["ja-trad", "茄子紺", "#824880", "なすこん"],
  ["ja-trad", "桜鼠", "#e9dfe5", "さくらねず"],
  ["ja-trad", "飴色", "#deb068", "あめいろ"],
  ["ja-trad", "黄朽葉色", "#d3a243", "きくちばいろ"],
  ["ja-trad", "翡翠色", "#38b48b", "ひすいいろ"],
  ["ja-trad", "二藍", "#915c8b", "ふたあい"],
  ["ja-trad", "鴇鼠", "#e4d2d8", "ときねず"],
  ["ja-trad", "駱駝色", "#bf794e", "らくだいろ"],
  ["ja-trad", "山吹茶", "#c89932", "やまぶきちゃ"],
  ["ja-trad", "青緑", "#00a497", "あおみどり"],
  ["ja-trad", "京紫", "#9d5b8b", "きょうむらさき"],
  ["ja-trad", "虹色", "#f6bfbc", "にじいろ"],
  ["ja-trad", "土色", "#bc763c", "つちいろ"],
  ["ja-trad", "芥子色", "#d0af4c", "からしいろ"],
  ["ja-trad", "水浅葱", "#80aba9", "みずあさぎ"],
  ["ja-trad", "蒲葡", "#7a4171", "えびぞめ"],
  ["ja-trad", "珊瑚色", "#f5b1aa", "さんごいろ"],
  ["ja-trad", "黄唐茶", "#b98c46", "きがらちゃ"],
  ["ja-trad", "豆がら茶", "#8b968d", "まめがらちゃ"],
  ["ja-trad", "錆浅葱", "#5c9291", "さびあさぎ"],
  ["ja-trad", "若紫", "#bc64a4", "わかむらさき"],
  ["ja-trad", "一斤染", "#f5b199", "いっこんぞめ"],
  ["ja-trad", "桑染", "#b79b5b", "くわぞめ"],
  ["ja-trad", "麹塵", "#6e7955", "きくじん"],
  ["ja-trad", "青碧", "#478384", "せいへき"],
  ["ja-trad", "紅紫", "#b44c97", "べにむらさき"],
  ["ja-trad", "宍色", "#efab93", "ししいろ"],
  ["ja-trad", "櫨色", "#b77b57", "はじいろ"],
  ["ja-trad", "山鳩色", "#767c6b", "やまばといろ"],
  ["ja-trad", "御召茶", "#43676b", "おめしちゃ"],
  ["ja-trad", "梅紫", "#aa4c8f", "うめむらさき"],
  ["ja-trad", "紅梅色", "#f2a0a1", "こうばいいろ"],
  ["ja-trad", "黄橡", "#b68d4c", "きつるばみ"],
  ["ja-trad", "利休鼠", "#888e7e", "りきゅうねずみ"],
  ["ja-trad", "湊鼠", "#80989b", "みなとねずみ"],
  ["ja-trad", "菖蒲色", "#cc7eb1", "あやめいろ"],
  ["ja-trad", "薄紅", "#f0908d", "うすべに"],
  ["ja-trad", "丁字染", "#ad7d4c", "ちょうじぞめ"],
  ["ja-trad", "海松茶", "#5a544b", "みるちゃ"],
  ["ja-trad", "高麗納戸", "#2c4f54", "こうらいなんど"],
  ["ja-trad", "紅藤色", "#cca6bf", "べにふじいろ"],
  ["ja-trad", "甚三紅", "#ee827c", "じんざもみ"],
  ["ja-trad", "香染", "#ad7d4c", "こうぞめ"],
  ["ja-trad", "藍海松茶", "#56564b", "あいみるちゃ"],
  ["ja-trad", "百入茶", "#1f3134", "ももしおちゃ"],
  ["ja-trad", "浅紫", "#c4a3bf", "あさむらさき"],
  ["ja-trad", "桃色", "#f09199", "ももいろ"],
  ["ja-trad", "枇杷茶", "#ae7c4f", "びわちゃ"],
  ["ja-trad", "藍媚茶", "#555647", "あいこびちゃ"],
  ["ja-trad", "錆鼠", "#47585c", "さびねず"],
  ["ja-trad", "紫水晶", "#e7e7eb", "むらさきすいしょう"],
  ["ja-trad", "鴇色", "#f4b3c2", "ときいろ"],
  ["ja-trad", "芝翫茶", "#ad7e4e", "しかんちゃ"],
  ["ja-trad", "千歳茶", "#494a41", "せんさいちゃ"],
  ["ja-trad", "錆鉄御納戸", "#485859", "さびてつおなんど"],
  ["ja-trad", "薄梅鼠", "#dcd6d9", "うすうめねず"],
  ["ja-trad", "撫子色", "#eebbcb", "なでしこいろ"],
  ["ja-trad", "焦香", "#ae7c58", "こがれこう"],
  ["ja-trad", "岩井茶", "#6b6f59", "いわいちゃ"],
  ["ja-trad", "藍鼠", "#6c848d", "あいねず"],
  ["ja-trad", "暁鼠", "#d3cfd9", "あかつきねず"],
  ["ja-trad", "灰梅", "#e8d3c7", "はいうめ"],
  ["ja-trad", "胡桃色", "#a86f4c", "くるみいろ"],
  ["ja-trad", "仙斎茶", "#474b42", "せんさいちゃ"],
  ["ja-trad", "錆御納戸", "#53727d", "さびおなんど"],
  ["ja-trad", "牡丹鼠", "#d3ccd6", "ぼたんねず"],
  ["ja-trad", "灰桜", "#e8d3d1", "はいざくら"],
  ["ja-trad", "渋紙色", "#946243", "しぶかみいろ"],
  ["ja-trad", "黒緑", "#333631", "くろみどり"],
  ["ja-trad", "舛花色", "#5b7e91", "ますはないろ"],
  ["ja-trad", "霞色", "#c8c2c6", "かすみいろ"],
  ["ja-trad", "淡紅藤", "#e6cde3", "あわべにふじ"],
  ["ja-trad", "朽葉色", "#917347", "くちばいろ"],
  ["ja-trad", "柳煤竹", "#5b6356", "やなぎすすたけ"],
  ["ja-trad", "熨斗目花色", "#426579", "のしめはないろ"],
  ["ja-trad", "藤鼠", "#a6a5c4", "ふじねず"],
  ["ja-trad", "石竹色", "#e5abbe", "せきちくいろ"],
  ["ja-trad", "桑茶", "#956f29", "くわちゃ"],
  ["ja-trad", "樺茶色", "#726250", "かばちゃいろ"],
  ["ja-trad", "御召御納戸", "#4c6473", "おめしおなんど"],
  ["ja-trad", "半色", "#a69abd", "はしたいろ"],
  ["ja-trad", "薄紅梅", "#e597b2", "うすこうばい"],
  ["ja-trad", "路考茶", "#8c7042", "ろこうちゃ"],
  ["ja-trad", "空五倍子色", "#9d896c", "うつぶしいろ"],
  ["ja-trad", "鉄御納戸", "#455765", "てつおなんど"],
  ["ja-trad", "薄色", "#a89dac", "うすいろ"],
  ["ja-trad", "桃花色", "#e198b4", "ももはないろ"],
  ["ja-trad", "国防色", "#7b6c3e", "こくぼうしょく"],
  ["ja-trad", "生壁色", "#94846a", "なまかべいろ"],
  ["ja-trad", "紺鼠", "#44617b", "こんねず"],
  ["ja-trad", "薄鼠", "#9790a4", "うすねず"],
  ["ja-trad", "水柿", "#e4ab9b", "みずがき"],
  ["ja-trad", "伽羅色", "#d8a373", "きゃらいろ"],
  ["ja-trad", "肥後煤竹", "#897858", "ひごすすたけ"],
  ["ja-trad", "藍鉄", "#393f4c", "あいてつ"],
  ["ja-trad", "鳩羽鼠", "#9e8b8e", "はとばねずみ"],
  ["ja-trad", "ときがら茶", "#e09e87", "ときがらちゃ"],
  ["ja-trad", "江戸茶", "#cd8c5c", "えどちゃ"],
  ["ja-trad", "媚茶", "#716246", "こびちゃ"],
  ["ja-trad", "青褐", "#393e4f", "あおかち"],
  ["ja-trad", "鳩羽色", "#95859c", "はとばいろ"],
  ["ja-trad", "退紅", "#d69090", "あらぞめ"],
  ["ja-trad", "樺色", "#cd5e3c", "かばいろ"],
  ["ja-trad", "白橡", "#cbb994", "しろつるばみ"],
  ["ja-trad", "褐返", "#203744", "かちかえし"],
  ["ja-trad", "桔梗鼠", "#95949a", "ききょうねず"],
  ["ja-trad", "薄柿", "#d4acad", "うすがき"],
  ["ja-trad", "紅鬱金", "#cb8347", "べにうこん"],
  ["ja-trad", "亜麻色", "#d6c6af", "あまいろ"],
  ["ja-trad", "褐色", "#4d4c61", "かちいろ"],
  ["ja-trad", "紫鼠", "#71686c", "むらさきねず"],
  ["ja-trad", "長春色", "#c97586", "ちょうしゅんいろ"],
  ["ja-trad", "土器色", "#c37854", "かわらけいろ"],
  ["ja-trad", "榛色", "#bfa46f", "はしばみいろ"],
  ["ja-trad", "月白", "#eaf4fc", "げっぱく"],
  ["ja-trad", "葡萄鼠", "#705b67", "ぶどうねずみ"],
  ["ja-trad", "梅鼠", "#c099a0", "うめねず"],
  ["ja-trad", "狐色", "#c38743", "きつねいろ"],
  ["ja-trad", "灰汁色", "#9e9478", "あくいろ"],
  ["ja-trad", "白菫色", "#eaedf7", "しろすみれいろ"],
  ["ja-trad", "濃色", "#634950", "こきいろ"],
  ["ja-trad", "鴇浅葱", "#b88884", "ときあさぎ"],
  ["ja-trad", "黄土色", "#c39143", "おうどいろ"],
  ["ja-trad", "利休茶", "#a59564", "りきゅうちゃ"],
  ["ja-trad", "白花色", "#e8ecef", "しらはないろ"],
  ["ja-trad", "紫鳶", "#5f414b", "むらさきとび"],
  ["ja-trad", "梅染", "#b48a76", "うめぞめ"],
  ["ja-trad", "琥珀色", "#bf783a", "こはくいろ"],
  ["ja-trad", "鶯茶", "#715c1f", "うぐいすちゃ"],
  ["ja-trad", "藍白", "#ebf6f7", "あいじろ"],
  ["ja-trad", "濃鼠", "#4f455c", "こいねず"],
  ["ja-trad", "蘇芳香", "#a86965", "すおうこう"],
  ["ja-trad", "赤茶", "#bb5535", "あかちゃ"],
  ["ja-trad", "木蘭色", "#c7b370", "もくらんじき"],
  ["ja-trad", "白藍", "#c1e4e9", "しらあい"],
  ["ja-trad", "藤煤竹", "#5a5359", "ふじすすたけ"],
  ["ja-trad", "浅蘇芳", "#a25768", "あさすおう"],
  ["ja-trad", "代赭", "#bb5520", "たいしゃ"],
  ["ja-trad", "砂色", "#dcd3b2", "すないろ"],
  ["ja-trad", "水色", "#bce2e8", "みずいろ"],
  ["ja-trad", "滅紫", "#594255", "けしむらさき"],
  ["ja-trad", "真朱", "#ec6d71", "まそお"],
  ["ja-trad", "煉瓦色", "#b55233", "れんがいろ"],
  ["ja-trad", "油色", "#a19361", "あぶらいろ"],
  ["ja-trad", "瓶覗", "#a2d7dd", "かめのぞき"],
  ["ja-trad", "紅消鼠", "#524748", "べにけしねずみ"],
  ["ja-trad", "赤紫", "#eb6ea5", "あかむらさき"],
  ["ja-trad", "雀茶", "#aa4f37", "すずめちゃ"],
  ["ja-trad", "利休色", "#8f8667", "りきゅういろ"],
  ["ja-trad", "秘色色", "#abced8", "ひそくいろ"],
  ["ja-trad", "似せ紫", "#513743", "にせむらさき"],
  ["ja-trad", "躑躅色", "#e95295", "つつじいろ"],
  ["ja-trad", "団十郎茶", "#9f563a", "だんじゅうろうちゃ"],
  ["ja-trad", "梅幸茶", "#887938", "ばいこうちゃ"],
  ["ja-trad", "空色", "#a0d8ef", "そらいろ"],
  ["ja-trad", "灰黄緑", "#e6eae3", "はいきみどり"],
  ["ja-trad", "牡丹色", "#e7609e", "ぼたんいろ"],
  ["ja-trad", "柿渋色", "#9f563a", "かきしぶいろ"],
  ["ja-trad", "璃寛茶", "#6a5d21", "りかんちゃ"],
  ["ja-trad", "勿忘草色", "#89c3eb", "わすれなぐさいろ"],
  ["ja-trad", "蕎麦切色", "#d4dcd6", "そばきりいろ"],
  ["ja-trad", "今様色", "#d0576b", "いまよういろ"],
  ["ja-trad", "紅鳶", "#9a493f", "べにとび"],
  ["ja-trad", "黄海松茶", "#918754", "きみるちゃ"],
  ["ja-trad", "青藤色", "#84a2d4", "あおふじいろ"],
  ["ja-trad", "薄雲鼠", "#d4dcda", "うすくもねず"],
  ["ja-trad", "中紅", "#c85179", "なかべに"],
  ["ja-trad", "灰茶", "#98623c", "はいちゃ"],
  ["ja-trad", "菜種油色", "#a69425", "なたねゆいろ"],
  ["ja-trad", "白群", "#83ccd2", "びゃくぐん"],
  ["ja-trad", "枯野色", "#d3cbc6", "かれのいろ"],
  ["ja-trad", "薔薇色", "#e9546b", "ばらいろ"],
  ["ja-trad", "茶色", "#965042", "ちゃいろ"],
  ["ja-trad", "青朽葉", "#ada250", "あおくちば"],
  ["ja-trad", "浅縹", "#84b9cb", "あさはなだ"],
  ["ja-trad", "潤色", "#c8c2be", "うるみいろ"],
  ["ja-trad", "韓紅", "#e95464", "からくれない"],
  ["ja-trad", "檜皮色", "#965036", "ひわだいろ"],
  ["ja-trad", "根岸色", "#938b4b", "ねぎしいろ"],
  ["ja-trad", "薄花色", "#698aab", "うすはないろ"],
  ["ja-trad", "利休白茶", "#b3ada0", "りきゅうしろちゃ"],
  ["ja-trad", "銀朱", "#c85554", "ぎんしゅ"],
  ["ja-trad", "鳶色", "#95483f", "とびいろ"],
  ["ja-trad", "鶸茶", "#8c8861", "ひわちゃ"],
  ["ja-trad", "納戸色", "#008899", "なんどいろ"],
  ["ja-trad", "茶鼠", "#a99e93", "ちゃねずみ"],
  ["ja-trad", "赤紅", "#c53d43", "あかべに"],
  ["ja-trad", "柿茶", "#954e2a", "かきちゃ"],
  ["ja-trad", "柳茶", "#a1a46d", "やなぎちゃ"],
  ["ja-trad", "浅葱色", "#00a3af", "あさぎいろ"],
  ["ja-trad", "胡桃染", "#a58f86", "くるみぞめ"],
  ["ja-trad", "紅緋", "#e83929", "べにひ"],
  ["ja-trad", "弁柄色", "#8f2e14", "べんがらいろ"],
  ["ja-trad", "海松色", "#726d40", "みるいろ"],
  ["ja-trad", "花浅葱", "#2a83a2", "はなあさぎ"],
  ["ja-trad", "江戸鼠", "#928178", "えどねず"],
  ["ja-trad", "赤", "#e60033", "あか"],
  ["ja-trad", "赤錆色", "#8a3319", "あかさびいろ"],
  ["ja-trad", "鶯色", "#928c36", "うぐいすいろ"],
  ["ja-trad", "新橋色", "#59b9c6", "しんばしいろ"],
  ["ja-trad", "煤色", "#887f7a", "すすいろ"],
  ["ja-trad", "猩々緋", "#e2041b", "しょうじょうひ"],
  ["ja-trad", "緑黄色", "#dccb18", "りょくおうしょく"],
  ["ja-trad", "天色", "#2ca9e1", "あまいろ"],
  ["ja-trad", "丁子茶", "#b4866b", "ちょうじちゃ"],
  ["ja-trad", "紅", "#d7003a", "くれない"],
  ["ja-trad", "栗梅", "#852e19", "くりうめ"],
  ["ja-trad", "鶸色", "#d7cf3a", "ひわいろ"],
  ["ja-trad", "露草色", "#38a1db", "つゆくさいろ"],
  ["ja-trad", "柴染", "#b28c6e", "ふしぞめ"],
  ["ja-trad", "深緋", "#c9171e", "こきひ"],
  ["ja-trad", "紅檜皮", "#7b4741", "べにひはだ"],
  ["ja-trad", "抹茶色", "#c5c56a", "まっちゃいろ"],
  ["ja-trad", "青", "#0095d9", "あお"],
  ["ja-trad", "宗伝唐茶", "#a16d5d", "そうでんからちゃ"],
  ["ja-trad", "緋色", "#d3381c", "ひいろ"],
  ["ja-trad", "海老茶", "#773c30", "えびちゃ"],
  ["ja-trad", "若草色", "#c3d825", "わかくさいろ"],
  ["ja-trad", "薄藍", "#0094c8", "うすあい"],
  ["ja-trad", "砺茶", "#9f6f55", "とのちゃ"],
  ["ja-trad", "赤丹", "#ce5242", "あかに"],
  ["ja-trad", "唐茶", "#783c1d", "からちゃ"],
  ["ja-trad", "黄緑", "#b8d200", "きみどり"],
  ["ja-trad", "縹色", "#2792c3", "はなだいろ"],
  ["ja-trad", "煎茶色", "#8c6450", "せんちゃいろ"],
  ["ja-trad", "紅赤", "#d9333f", "べにあか"],
  ["ja-trad", "栗色", "#762f07", "くりいろ"],
  ["ja-trad", "若芽色", "#e0ebaf", "わかめいろ"],
  ["ja-trad", "紺碧", "#007bbb", "こんぺき"],
  ["ja-trad", "銀煤竹", "#856859", "ぎんすすだけ"],
  ["ja-trad", "臙脂", "#b94047", "えんじ"],
  ["ja-trad", "赤銅色", "#752100", "しゃくどういろ"],
  ["ja-trad", "若菜色", "#d8e698", "わかないろ"],
  ["ja-trad", "薄群青", "#5383c3", "うすぐんじょう"],
  ["ja-trad", "黄枯茶", "#765c47", "きがらちゃ"],
  ["ja-trad", "朱・緋", "#ba2636", "あけ"],
  ["ja-trad", "錆色", "#6c3524", "さびいろ"],
  ["ja-trad", "若苗色", "#c7dc68", "わかなえいろ"],
  ["ja-trad", "薄花桜", "#5a79ba", "うすはなざくら"],
  ["ja-trad", "煤竹色", "#6f514c", "すすたけいろ"],
  ["ja-trad", "茜色", "#b7282e", "あかねいろ"],
  ["ja-trad", "赤褐色", "#683f36", "せっかっしょく"],
  ["ja-trad", "青丹", "#99ab4e", "あおに"],
  ["ja-trad", "群青色", "#4c6cb3", "ぐんじょういろ"],
  ["ja-trad", "焦茶", "#6f4b3e", "こげちゃ"],
  ["ja-trad", "紅海老茶", "#a73836", "べにえびちゃ"],
  ["ja-trad", "茶褐色", "#664032", "ちゃかっしょく"],
  ["ja-trad", "草色", "#7b8d42", "くさいろ"],
  ["ja-trad", "杜若色", "#3e62ad", "かきつばたいろ"],
  ["ja-trad", "黒橡", "#544a47", "くろつるばみ"],
  ["ja-trad", "蘇芳", "#9e3d3f", "すおう"],
  ["ja-trad", "栗皮茶", "#6d3c32", "くりかわちゃ"],
  ["ja-trad", "苔色", "#69821b", "こけいろ"],
  ["ja-trad", "瑠璃色", "#1e50a2", "るりいろ"],
  ["ja-trad", "憲法色", "#543f32", "けんぽういろ"],
  ["ja-trad", "真紅", "#a22041", "しんく"],
  ["ja-trad", "黒茶", "#583822", "くろちゃ"],
  ["ja-trad", "萌黄", "#aacf53", "もえぎ"],
  ["ja-trad", "薄縹", "#507ea4", "うすはなだ"],
  ["ja-trad", "涅色", "#554738", "くりいろ"],
  ["ja-trad", "濃紅", "#a22041", "こいくれない"],
  ["ja-trad", "葡萄茶", "#6c2c2f", "えびちゃ"],
  ["ja-trad", "苗色", "#b0ca71", "なえいろ"],
  ["ja-trad", "瑠璃紺", "#19448e", "るりこん"],
  ["ja-trad", "檳榔子染", "#433d3c", "びんろうじぞめ"],
  ["ja-trad", "象牙色", "#f8f4e6", "ぞうげいろ"],
  ["ja-trad", "葡萄色", "#640125", "えびいろ"],
  ["ja-trad", "若葉色", "#b9d08b", "わかばいろ"],
  ["ja-trad", "紺瑠璃", "#164a84", "こんるり"],
  ["ja-trad", "黒鳶", "#432f2f", "くろとび"],
  ["ja-trad", "練色", "#ede4cd", "ねりいろ"],
  ["ja-trad", "萱草色", "#f8b862", "かんぞういろ"],
  ["ja-trad", "松葉色", "#839b5c", "まつばいろ"],
  ["ja-trad", "藍色", "#165e83", "あいいろ"],
  ["ja-trad", "赤墨", "#3f312b", "あかすみ"],
  ["ja-trad", "灰白色", "#e9e4d4", "かいはくしょく"],
  ["ja-trad", "柑子色", "#f6ad49", "こうじいろ"],
  ["ja-trad", "夏虫色", "#cee4ae", "なつむしいろ"],
  ["ja-trad", "青藍", "#274a78", "せいらん"],
  ["ja-trad", "黒紅", "#302833", "くろべに"],
  ["ja-trad", "蒸栗色", "#ebe1a9", "むしぐりいろ"],
  ["ja-trad", "金茶", "#f39800", "きんちゃ"],
  ["ja-trad", "鶸萌黄", "#82ae46", "ひわもえぎ"],
  ["ja-trad", "深縹", "#2a4073", "こきはなだ"],
  ["ja-trad", "白", "#ffffff", "しろ"],
  ["ja-trad", "女郎花", "#f2f2b0", "おみなえし"],
  ["ja-trad", "蜜柑色", "#f08300", "みかんいろ"],
  ["ja-trad", "柳色", "#a8c97f", "やなぎいろ"],
  ["ja-trad", "紺色", "#223a70", "こんいろ"],
  ["ja-trad", "胡粉色", "#fffffc", "ごふんいろ"],
  ["ja-trad", "枯草色", "#e4dc8a", "かれくさいろ"],
  ["ja-trad", "鉛丹色", "#ec6d51", "えんたんいろ"],
  ["ja-trad", "青白橡", "#9ba88d", "あおしろつるばみ"],
  ["ja-trad", "紺青", "#192f60", "こんじょう"],
  ["ja-trad", "卯の花色", "#f7fcfe", "うのはないろ"],
  ["ja-trad", "淡黄", "#f8e58c", "たんこう"],
  ["ja-trad", "黄丹", "#ee7948", "おうに"],
  ["ja-trad", "柳鼠", "#c8d5bb", "やなぎねず"],
  ["ja-trad", "留紺", "#1c305c", "とめこん"],
  ["ja-trad", "白磁", "#f8fbf8", "はくじ"],
  ["ja-trad", "白茶", "#ddbb99", "しらちゃ"],
  ["ja-trad", "柿色", "#ed6d3d", "かきいろ"],
  ["ja-trad", "裏葉柳", "#c1d8ac", "うらはやなぎ"],
  ["ja-trad", "濃藍", "#0f2350", "こいあい"],
  ["ja-trad", "生成り色", "#fbfaf5", "きなりいろ"],
  ["ja-trad", "赤白橡", "#d7a98c", "あかしろつるばみ"],
  ["ja-trad", "黄赤", "#ec6800", "きあか"],
  ["ja-trad", "山葵色", "#a8bf93", "わさびいろ"],
  ["ja-trad", "鉄紺", "#17184b", "てつこん"],
  ["ja-trad", "乳白色", "#f3f3f3", "にゅうはくしょく"],
  ["ja-trad", "洗柿", "#f2c9ac", "あらいがき"],
  ["ja-trad", "人参色", "#ec6800", "にんじんいろ"],
  ["ja-trad", "老竹色", "#769164", "おいたけいろ"],
  ["ja-trad", "漆黒", "#0d0015", "しっこく"],
  ["ja-trad", "白練", "#f3f3f2", "しろねり"],
  ["ja-trad", "鳥の子色", "#fff1cf", "とりのこいろ"],
  ["ja-trad", "橙色", "#ee7800", "だいだいいろ"],
  ["ja-trad", "白緑", "#d6e9ca", "びゃくろく"],
  ["ja-trad", "淡藤色", "#bbc8e6", "あわふじいろ"],
  ["ja-trad", "素色", "#eae5e3", "そしょく"],
  ["ja-trad", "蜂蜜色", "#fddea5", "はちみついろ"],
  ["ja-trad", "照柿", "#eb6238", "てりがき"],
  ["ja-trad", "淡萌黄", "#93ca76", "うすもえぎ"],
  ["ja-trad", "藤色", "#bbbcde", "ふじいろ"],
  ["ja-trad", "白梅鼠", "#e5e4e6", "しらうめねず"],
  ["ja-trad", "肌色", "#fce2c4", "はだいろ"],
  ["ja-trad", "赤橙", "#ea5506", "あかだいだい"],
  ["ja-trad", "柳染", "#93b881", "やなぎぞめ"],
  ["ja-trad", "紅掛空色", "#8491c3", "べにかけそらいろ"],
  ["ja-trad", "白鼠", "#dcdddd", "しろねず"],
  ["ja-trad", "薄卵色", "#fde8d0", "うすたまごいろ"],
  ["ja-trad", "金赤", "#ea5506", "きんあか"],
  ["ja-trad", "薄萌葱", "#badcad", "うすもえぎ"],
  ["ja-trad", "紅碧", "#8491c3", "べにみどり"],
  ["ja-trad", "絹鼠", "#dddcd6", "きぬねず"],
  ["ja-trad", "雄黄", "#f9c89b", "ゆうおう"],
  ["ja-trad", "朱色", "#eb6101", "しゅいろ"],
  ["ja-trad", "深川鼠", "#97a791", "ふかがわねずみ"],
  ["ja-trad", "紺桔梗", "#4d5aaf", "こんききょう"],
  ["ja-trad", "灰青", "#c0c6c9", "はいあお"],
  ["ja-trad", "洒落柿", "#f7bd8f", "しゃれがき"],
  ["ja-trad", "小麦色", "#e49e61", "こむぎいろ"],
  ["ja-trad", "若緑", "#98d98e", "わかみどり"],
  ["ja-trad", "花色", "#4d5aaf", "はないろ"],
  ["ja-trad", "銀鼠", "#afafb0", "ぎんねず"],
  ["ja-trad", "赤香", "#f6b894", "あかこう"],
  ["ja-trad", "丹色", "#e45e32", "にいろ"],
  ["ja-trad", "浅緑", "#88cb7f", "あさみどり"],
  ["ja-trad", "紺藍", "#4a488e", "こんあい"],
  ["ja-trad", "薄鈍", "#adadad", "うすにび"],
  ["ja-trad", "砥粉色", "#f4dda5", "とのこいろ"],
  ["ja-trad", "黄茶", "#e17b34", "きちゃ"],
  ["ja-trad", "薄緑", "#69b076", "うすみどり"],
  ["ja-trad", "紅桔梗", "#4d4398", "べにききょう"],
  ["ja-trad", "薄墨色", "#a3a3a2", "うすずみいろ"],
  ["ja-trad", "肉色", "#f1bf99", "にくいろ"],
  ["ja-trad", "肉桂色", "#dd7a56", "にっけいいろ"],
  ["ja-trad", "青鈍", "#6b7b6e", "あおにび"],
  ["ja-trad", "桔梗色", "#5654a2", "ききょういろ"],
  ["ja-trad", "錫色", "#9ea1a3", "すずいろ"],
  ["ja-trad", "人色", "#f1bf99", "ひといろ"],
  ["ja-trad", "赤朽葉色", "#db8449", "あかくちばいろ"],
  ["ja-trad", "青磁鼠", "#bed2c3", "せいじねず"],
  ["ja-trad", "藤納戸", "#706caa", "ふじなんど"],
  ["ja-trad", "素鼠", "#9fa0a0", "すねずみ"],
  ["ja-trad", "丁子色", "#efcd9a", "ちょうじいろ"],
  ["ja-trad", "黄櫨染", "#d66a35", "こうろぜん"],
  ["ja-trad", "薄青", "#93b69c", "うすあお"],
  ["ja-trad", "紅掛花色", "#68699b", "べにかけはないろ"],
  ["ja-trad", "鼠色", "#949495", "ねずみいろ"],
  ["ja-trad", "香色", "#efcd9a", "こういろ"],
  ["ja-trad", "蒲公英色", "#ffd900", "たんぽぽいろ"],
  ["ja-trad", "錆青磁", "#a6c8b2", "さびせいじ"],
  ["ja-trad", "紫苑色", "#867ba9", "しおんいろ"],
  ["ja-trad", "源氏鼠", "#888084", "げんじねず"],
  ["ja-trad", "薄香", "#f0cfa0", "うすこう"],
  ["ja-trad", "黄色", "#ffd900", "きいろ"],
  ["ja-trad", "緑青色", "#47885e", "ろくしょういろ"],
  ["ja-trad", "白藤色", "#dbd0e6", "しらふじいろ"],
  ["ja-trad", "灰色", "#7d7d7d", "はいいろ"],
  ["ja-trad", "浅黄", "#edd3a1", "うすき"],
  ["ja-trad", "中黄", "#ffea00", "ちゅうき"],
  ["ja-trad", "千歳緑", "#316745", "ちとせみどり"],
  ["ja-trad", "藤紫", "#a59aca", "ふじむらさき"],
  ["ja-trad", "鉛色", "#7b7c7d", "なまりいろ"],
  ["ja-trad", "枯色", "#e0c38c", "かれいろ"],
  ["ja-trad", "菜の花色", "#ffec47", "なのはないろ"],
  ["ja-trad", "若竹色", "#68be8d", "わかたけいろ"],
  ["ja-trad", "菫色", "#7058a3", "すみれいろ"],
  ["ja-trad", "鈍色", "#727171", "にびいろ"],
  ["ja-trad", "淡香", "#f3bf88", "うすこう"],
  ["ja-trad", "黄檗色", "#fef263", "きはだいろ"],
  ["ja-trad", "緑", "#3eb370", "みどり"],
  ["ja-trad", "青紫", "#674598", "あおむらさき"],
  ["ja-trad", "墨", "#595857", "すみ"],
  ["ja-trad", "杏色", "#f7b977", "あんずいろ"],
  ["ja-trad", "卵色", "#fcd575", "たまごいろ"],
  ["ja-trad", "常磐色", "#007b43", "ときわいろ"],
  ["ja-trad", "丼鼠", "#595455", "どぶねずみ"],
  ["ja-trad", "東雲色", "#f19072", "しののめいろ"],
  ["ja-trad", "花葉色", "#fbd26b", "はなばいろ"],
  ["ja-trad", "千草鼠", "#bed3ca", "ちぐさねず"],
  ["ja-trad", "竜胆色", "#9079ad", "りんどういろ"],
  ["ja-trad", "消炭色", "#524e4d", "けしずみいろ"],
  ["ja-trad", "曙色", "#f19072", "あけぼのいろ"],
  ["ja-trad", "刈安色", "#f5e56b", "かりやすいろ"],
  ["ja-trad", "千草色", "#92b5a9", "ちぐさいろ"],
  ["ja-trad", "江戸紫", "#745399", "えどむらさき"],
  ["ja-trad", "藍墨茶", "#474a4d", "あいすみちゃ"],
  ["ja-trad", "珊瑚朱色", "#ee836f", "さんごしゅいろ"],
  ["ja-trad", "玉蜀黍色", "#eec362", "とうもろこしいろ"],
  ["ja-trad", "青磁色", "#7ebea5", "せいじいろ"],
  ["ja-trad", "本紫", "#65318e", "ほんむらさき"],
  ["ja-trad", "羊羹色", "#383c3c", "ようかんいろ"],
  ["ja-trad", "深支子", "#eb9b6f", "こきくちなし"],
  ["ja-trad", "金糸雀色", "#ebd842", "かなりあいろ"],
  ["ja-trad", "青竹色", "#7ebeab", "あおたけいろ"],
  ["ja-trad", "蝋色", "#2b2b2b", "ろういろ"],
  ["ja-trad", "纁", "#e0815e", "そひ"],
  ["ja-trad", "黄支子色", "#ffdb4f", "きくちなしいろ"],
  ["ja-trad", "常磐緑", "#028760", "ときわみどり"],
  ["ja-trad", "深紫", "#493759", "ふかむらさき"],
  ["ja-trad", "黒", "#2b2b2b", "くろ"],
  ["ja-trad", "浅緋", "#df7163", "うすきひ"],
  ["ja-trad", "支子色", "#fbca4d", "くちなしいろ"],
  ["ja-trad", "木賊色", "#3b7960", "とくさいろ"],
  ["ja-trad", "紫黒", "#2e2930", "しこく"],
  ["ja-trad", "烏羽色", "#180614", "からすばいろ"],
  ["ja-trad", "真赭", "#d57c6b", "まそほ"],
  ["ja-trad", "向日葵色", "#fcc800", "ひまわりいろ"],
  ["ja-trad", "天鵞絨", "#2f5d50", "びろうど"],
  ["ja-trad", "紫", "#884898", "むらさき"],
  ["ja-trad", "鉄黒", "#281a14", "てつぐろ"],
  ["ja-trad", "洗朱", "#d0826c", "あらいしゅ"],
  ["ja-trad", "山吹色", "#f8b500", "やまぶきいろ"],
  ["ja-trad", "虫襖", "#3a5b52", "むしあお"],
  ["ja-trad", "薄葡萄", "#c0a2c7", "うすぶどう"],
  ["ja-trad", "濡羽色", "#000b00", "ぬればいろ"],
  ["ja-trad", "遠州茶", "#ca8269", "えんしゅうちゃ"],
  ["ja-trad", "鬱金色", "#fabf14", "うこんいろ"],
  ["ja-trad", "革色", "#475950", "かわいろ"],
  ["ja-trad", "紫紺", "#460e44", "しこん"],
  ["ja-trad", "黒檀", "#250d00", "こくたん"],
  ["ja-trad", "紅樺色", "#bb5548", "べにかばいろ"],
  ["ja-trad", "藤黄", "#f7c114", "とうおう"],
  ["ja-trad", "深緑", "#00552e", "ふかみどり"],
  ["ja-trad", "暗紅色", "#74325c", "あんこうしょく"],
  ["ja-trad", "憲法黒茶", "#241a08", "けんぽうくろちゃ"],
  ["ja-trad", "赭", "#ab6953", "そほ"],
  ["ja-trad", "金色", "#e6b422", "こんじき"],
  ["ja-trad", "鉄色", "#005243", "てついろ"],
  ["ja-trad", "桑の実色", "#55295b", "くわのみいろ"],
  ["ja-trad", "暗黒色", "#16160e", "あんこくしょく"],
  ["tok", "loje", "#e50000"],
  ["tok", "loje jelo", "#f97306"],
  ["tok", "jelo", "#ffff14"],
  ["tok", "laso", "#0343df"],
  ["tok", "laso", "#15b01a"],
  ["tok", "laso jelo", "#aaff32"],
  ["tok", "laso kasi", "#5ca904"],
  ["tok", "laso telo", "#029386"],
  ["tok", "laso sewi", "#75bbfd"],
  ["tok", "laso pimeja", "#00035b"],
  ["tok", "laso pimeja", "#033500"],
  ["tok", "laso walo", "#d0fefe"],
  ["tok", "laso walo", "#c7fdb5"],
  ["tok", "loje laso", "#7e1e9c"],
  ["tok", "loje laso", "#c20078"],
  ["tok", "loje laso walo", "#c79fef"],
  ["tok", "loje laso pimeja", "#35063e"],
  ["tok", "loje walo", "#ff81c0"],
  ["tok", "loje pimeja", "#653700"],
  ["tok", "loje pimeja", "#840000"],
  ["tok", "jelo pimeja", "#6e750e"],
  ["tok", "jelo pimeja", "#ceb301"],
  ["tok", "jelo walo", "#e6daa6"],
  ["tok", "walo", "#ffffff"],
  ["tok", "walo pimeja", "#929591"],
  ["tok", "pimeja", "#000000"],
];
