// 职责：DOM 元素注册表。getElementById 一次性查全（app.js 在 </body> 前加载、DOM 已就绪）。
// 所有 UI 模块直接 import { els }，无需经 ctx 注入（纯查表、零构造依赖）。
//
// 类型（candidate 4）：这些 id 都是 index.html 里静态存在的元素，app.js 在 DOM 就绪后才 import els，
// 故断言**非空**——消费方拿到 HTMLElement（而非 HTMLElement|null），不必到处 `!`/`?.`。
// 个别需要更窄类型（HTMLInputElement 等）的，待该消费方入门时再 byId<T>("id") 收窄。
function byId<T extends HTMLElement = HTMLElement>(id: string): T {
  return document.getElementById(id) as T;
}

export const els = {
  board: byId("board"),
  topBar: byId("topBar"),
  zoomLabel: byId("zoomLabel"),
  canvasSizeLabel: byId("canvasSizeLabel"),
  statusLabel: byId("statusLabel"),
  versionLabel: byId("versionLabel"),
  leftDialMount: byId("leftDialMount"),   // <LeftDial> Vue 组件挂载点（size/opacity/笔指示/popup）
  undoBtn: byId("undoButton"),
  redoBtn: byId("redoButton"),
  layersBtn: byId("layersButton"),
  layersPanel: byId("layersPanel"),
  layersPanelHead: byId("layersPanelHead"),
  layersPanelClose: byId("layersPanelClose"),
  layersList: byId("layersList"),
  layersCountLabel: byId("layersCountLabel"),
  layerAddBtn: byId<HTMLButtonElement>("layerAddBtn"),
  // v123：del/up/down 挪进 per-row "⋯" 菜单；footer 只剩 layerAddBtn
  menuBtn: byId("menuButton"),
  menuPanel: byId("menuPanel"),
  menuLongPressPick: byId("menuLongPressPick"),
  menuSingleFingerDraw: byId("menuSingleFingerDraw"),
  menuPressureSize: byId("menuPressureSize"),
  menuPressureOpacity: byId("menuPressureOpacity"),
  menuTheme: byId("menuTheme"),
  menuClear: byId("menuClear"),
  // v120 (user：「导出项目和导出语义分开 + 小扳手」)
  // 旧 5 项 (menuImport / menuExportPng/Jpg/Ora/Psd / menuClipboardCopy/Paste) → 新 3 行
  menuExportProject: byId("menuExportProject"),
  menuExportProjectConfig: byId("menuExportProjectConfig"),
  menuExportImage: byId("menuExportImage"),
  menuExportImageConfig: byId("menuExportImageConfig"),
  menuImportImage: byId("menuImportImage"),
  menuImportImageConfig: byId("menuImportImageConfig"),
  menuFit: byId("menuFit"),
  // v109: brushPanel + brush* sliders 撤了（平滑 per-preset，进 brush settings 调）
  topSaveBtn: byId("topSaveBtn"),
  topAdjustBtn: byId("topAdjustBtn"),
  adjustPopup: byId("adjustPopup"),
  // v110 crop / resample / adjust
  resampleBackdrop: byId("resampleBackdrop"),
  resampleSheet: byId("resampleSheet"),
  resampleW: byId("resampleW"),
  resampleH: byId("resampleH"),
  resampleLock: byId("resampleLock"),
  resampleMode: byId("resampleMode"),
  resampleCancel: byId("resampleCancel"),
  resampleConfirm: byId("resampleConfirm"),
  adjustPanel: byId("adjustPanel"),
  adjustPanelHead: byId("adjustPanelHead"),
  adjustPanelTitle: byId("adjustPanelTitle"),
  adjustParamsBody: byId("adjustParamsBody"),
  // v123 topGalleryBtn 撤了，图库挪进菜单 (id=menuGallery)
  menuGallery: byId("menuGallery"),
  menuReference: byId("menuReference"),
  menuResetBrushRack: byId("menuResetBrushRack"),
  menuForcePwaReset: byId("menuForcePwaReset"),
  menuSmoothDev: byId("menuSmoothDev"),
  referencePanel: byId("referencePanel"),
  referencePanelHead: byId("referencePanelHead"),
  referencePanelClose: byId("referencePanelClose"),
  referenceBody: byId("referenceBody"),
  referenceCanvas: byId("referenceCanvas"),
  referenceEmpty: byId("referenceEmpty"),
  referenceLoadBtn: byId("referenceLoadBtn"),
  referenceLiveBtn: byId("referenceLiveBtn"),
  referenceFitBtn: byId("referenceFitBtn"),
  referenceFileInput: byId("referenceFileInput"),
  galleryFull: byId("galleryFull"),
  galleryCloseBtn: byId("galleryCloseBtn"),
  galleryAddBtn: byId("galleryAddBtn"),
  galleryAddPopup: byId("galleryAddPopup"),
  galleryTrashBtn: byId("galleryTrashBtn"),
  galleryTrashBar: byId("galleryTrashBar"),
  galleryTrashBack: byId("galleryTrashBack"),
  galleryTrashMenuBtn: byId("galleryTrashMenuBtn"),
  galleryTrashMenuPopup: byId("galleryTrashMenuPopup"),
  galleryEmptyTrashLocalBtn: byId("galleryEmptyTrashLocalBtn"),
  galleryEmptyTrashCloudBtn: byId("galleryEmptyTrashCloudBtn"),
  addNewFolder: byId("addNewFolder"),
  addNew: byId("addNew"),
  addImportPhoto: byId("addImportPhoto"),
  addImportClipboard: byId("addImportClipboard"),
  cloudIconBtn: byId("cloudIconBtn"),
  cloudAccountPopup: byId("cloudAccountPopup"),
  cloudAccountInfo: byId("cloudAccountInfo"),
  cloudSignInBtn: byId("cloudSignInBtn"),
  cloudSignOutBtn: byId("cloudSignOutBtn"),
  cloudRefreshBtn: byId("cloudRefreshBtn"),
  galleryFootUsage: byId("galleryFootUsage"),
  galleryFootVersion: byId("galleryFootVersion"),
  galleryMenuBtn: byId("galleryMenuBtn"),
  galleryMenuPopup: byId("galleryMenuPopup"),
  galleryMenuVersion: byId("galleryMenuVersion"),
  galleryMenuForceUpdate: byId("galleryMenuForceUpdate"),
  galleryMenuTheme: byId("galleryMenuTheme"),
  galleryMenuLock: byId("galleryMenuLock"),
  newDocBackdrop: byId("newDocBackdrop"),
  newDocSheet: byId("newDocSheet"),
  newDocName: byId("newDocName"),
  newDocCustomRow: byId("newDocCustomRow"),
  newDocW: byId("newDocW"),
  newDocH: byId("newDocH"),
  newDocConfirm: byId("newDocConfirm"),
  newDocCancel: byId("newDocCancel"),
  menuRename: byId("menuRename"),
  menuSaveAs: byId("menuSaveAs"),
  menuRevertToOpen: byId("menuRevertToOpen"),
  menuEncrypt: byId("menuEncrypt"),
  menuEncryptLabel: byId("menuEncryptLabel"),
  topEncLock: byId("topEncLock"),
  menuCheckerboard: byId("menuCheckerboard"),
  menuPixelGrid: byId("menuPixelGrid"),
  menuFps: byId("menuFps"),
  menuCheckUpdate: byId("menuCheckUpdate"),
  oraFileInput: byId<HTMLInputElement>("oraFileInput"),
  genericBackdrop: byId("genericBackdrop"),
  genericSheet: byId("genericSheet"),
  genericSheetTitle: byId("genericSheetTitle"),
  genericSheetMessage: byId("genericSheetMessage"),
  genericSheetInput: byId("genericSheetInput"),
  genericSheetConfirm: byId("genericSheetConfirm"),
  genericSheetCancel: byId("genericSheetCancel"),
  toolBtns: [...document.querySelectorAll<HTMLElement>(".tool[data-tool]")],
  activeSwatch: byId("activeSwatch"),
  // 浮动色板
  colorPanel: byId("colorPanel"),
  colorPanelHead: byId("colorPanelHead"),
  colorPanelClose: byId("colorPanelClose"),
  colorPanelBody: document.querySelector("#colorPanel .float-panel-body"),  // 色轮 Vue 组件挂载点
  // clear sheet
  clearSheet: byId("clearSheet"),
  clearBackdrop: byId("clearBackdrop"),
  // update toast
  updateToast: byId("updateToast"),
  updateReload: byId("updateToastReload"),
  updateDismiss: byId("updateToastDismiss"),
};
