// 职责：DOM 元素注册表。getElementById 一次性查全（app.js 在 </body> 前加载、DOM 已就绪）。
// 所有 UI 模块直接 import { els }，无需经 ctx 注入（纯查表、零构造依赖）。

export const els = {
  board: document.getElementById("board"),
  topBar: document.getElementById("topBar"),
  zoomLabel: document.getElementById("zoomLabel"),
  canvasSizeLabel: document.getElementById("canvasSizeLabel"),
  statusLabel: document.getElementById("statusLabel"),
  versionLabel: document.getElementById("versionLabel"),
  leftDialMount: document.getElementById("leftDialMount"),   // <LeftDial> Vue 组件挂载点（size/opacity/笔指示/popup）
  undoBtn: document.getElementById("undoButton"),
  redoBtn: document.getElementById("redoButton"),
  layersBtn: document.getElementById("layersButton"),
  layersPanel: document.getElementById("layersPanel"),
  layersPanelHead: document.getElementById("layersPanelHead"),
  layersPanelClose: document.getElementById("layersPanelClose"),
  layersList: document.getElementById("layersList"),
  layersCountLabel: document.getElementById("layersCountLabel"),
  layerAddBtn: document.getElementById("layerAddBtn"),
  // v123：del/up/down 挪进 per-row "⋯" 菜单；footer 只剩 layerAddBtn
  menuBtn: document.getElementById("menuButton"),
  menuPanel: document.getElementById("menuPanel"),
  menuLongPressPick: document.getElementById("menuLongPressPick"),
  menuPressureSize: document.getElementById("menuPressureSize"),
  menuPressureOpacity: document.getElementById("menuPressureOpacity"),
  menuTheme: document.getElementById("menuTheme"),
  menuClear: document.getElementById("menuClear"),
  // v120 (user：「导出项目和导出语义分开 + 小扳手」)
  // 旧 5 项 (menuImport / menuExportPng/Jpg/Ora/Psd / menuClipboardCopy/Paste) → 新 3 行
  menuExportProject: document.getElementById("menuExportProject"),
  menuExportProjectConfig: document.getElementById("menuExportProjectConfig"),
  menuExportImage: document.getElementById("menuExportImage"),
  menuExportImageConfig: document.getElementById("menuExportImageConfig"),
  menuImportImage: document.getElementById("menuImportImage"),
  menuImportImageConfig: document.getElementById("menuImportImageConfig"),
  menuFit: document.getElementById("menuFit"),
  menuBrushSettings: document.getElementById("menuBrushSettings"),
  // v109: brushPanel + brush* sliders 撤了（平滑 per-preset，进 brush settings 调）
  topSaveBtn: document.getElementById("topSaveBtn"),
  topAdjustBtn: document.getElementById("topAdjustBtn"),
  adjustPopup: document.getElementById("adjustPopup"),
  // v110 crop / resample / adjust
  resampleBackdrop: document.getElementById("resampleBackdrop"),
  resampleSheet: document.getElementById("resampleSheet"),
  resampleW: document.getElementById("resampleW"),
  resampleH: document.getElementById("resampleH"),
  resampleLock: document.getElementById("resampleLock"),
  resampleMode: document.getElementById("resampleMode"),
  resampleCancel: document.getElementById("resampleCancel"),
  resampleConfirm: document.getElementById("resampleConfirm"),
  adjustPanel: document.getElementById("adjustPanel"),
  adjustPanelHead: document.getElementById("adjustPanelHead"),
  adjustPanelTitle: document.getElementById("adjustPanelTitle"),
  adjustParamsBody: document.getElementById("adjustParamsBody"),
  // v123 topGalleryBtn 撤了，图库挪进菜单 (id=menuGallery)
  menuGallery: document.getElementById("menuGallery"),
  menuReference: document.getElementById("menuReference"),
  menuResetBrushRack: document.getElementById("menuResetBrushRack"),
  menuForcePwaReset: document.getElementById("menuForcePwaReset"),
  menuSmoothDev: document.getElementById("menuSmoothDev"),
  referencePanel: document.getElementById("referencePanel"),
  referencePanelHead: document.getElementById("referencePanelHead"),
  referencePanelClose: document.getElementById("referencePanelClose"),
  referenceBody: document.getElementById("referenceBody"),
  referenceCanvas: document.getElementById("referenceCanvas"),
  referenceEmpty: document.getElementById("referenceEmpty"),
  referenceLoadBtn: document.getElementById("referenceLoadBtn"),
  referenceLiveBtn: document.getElementById("referenceLiveBtn"),
  referenceFitBtn: document.getElementById("referenceFitBtn"),
  referenceFileInput: document.getElementById("referenceFileInput"),
  galleryFull: document.getElementById("galleryFull"),
  galleryCloseBtn: document.getElementById("galleryCloseBtn"),
  galleryAddBtn: document.getElementById("galleryAddBtn"),
  galleryAddPopup: document.getElementById("galleryAddPopup"),
  galleryTrashBtn: document.getElementById("galleryTrashBtn"),
  galleryTrashBar: document.getElementById("galleryTrashBar"),
  galleryTrashBack: document.getElementById("galleryTrashBack"),
  galleryTrashMenuBtn: document.getElementById("galleryTrashMenuBtn"),
  galleryTrashMenuPopup: document.getElementById("galleryTrashMenuPopup"),
  galleryEmptyTrashBtn: document.getElementById("galleryEmptyTrashBtn"),
  addNewFolder: document.getElementById("addNewFolder"),
  addNew: document.getElementById("addNew"),
  addImportPhoto: document.getElementById("addImportPhoto"),
  addImportClipboard: document.getElementById("addImportClipboard"),
  cloudIconBtn: document.getElementById("cloudIconBtn"),
  cloudAccountPopup: document.getElementById("cloudAccountPopup"),
  cloudAccountInfo: document.getElementById("cloudAccountInfo"),
  cloudSignInBtn: document.getElementById("cloudSignInBtn"),
  cloudSignOutBtn: document.getElementById("cloudSignOutBtn"),
  cloudRefreshBtn: document.getElementById("cloudRefreshBtn"),
  galleryFootUsage: document.getElementById("galleryFootUsage"),
  galleryFootVersion: document.getElementById("galleryFootVersion"),
  galleryMenuBtn: document.getElementById("galleryMenuBtn"),
  galleryMenuPopup: document.getElementById("galleryMenuPopup"),
  galleryMenuVersion: document.getElementById("galleryMenuVersion"),
  galleryMenuForceUpdate: document.getElementById("galleryMenuForceUpdate"),
  galleryMenuTheme: document.getElementById("galleryMenuTheme"),
  newDocBackdrop: document.getElementById("newDocBackdrop"),
  newDocSheet: document.getElementById("newDocSheet"),
  newDocName: document.getElementById("newDocName"),
  newDocCustomRow: document.getElementById("newDocCustomRow"),
  newDocW: document.getElementById("newDocW"),
  newDocH: document.getElementById("newDocH"),
  newDocConfirm: document.getElementById("newDocConfirm"),
  newDocCancel: document.getElementById("newDocCancel"),
  menuRename: document.getElementById("menuRename"),
  menuSaveAs: document.getElementById("menuSaveAs"),
  menuRevertToOpen: document.getElementById("menuRevertToOpen"),
  menuCheckerboard: document.getElementById("menuCheckerboard"),
  menuPixelGrid: document.getElementById("menuPixelGrid"),
  menuCheckUpdate: document.getElementById("menuCheckUpdate"),
  oraFileInput: document.getElementById("oraFileInput"),
  genericBackdrop: document.getElementById("genericBackdrop"),
  genericSheet: document.getElementById("genericSheet"),
  genericSheetTitle: document.getElementById("genericSheetTitle"),
  genericSheetMessage: document.getElementById("genericSheetMessage"),
  genericSheetInput: document.getElementById("genericSheetInput"),
  genericSheetConfirm: document.getElementById("genericSheetConfirm"),
  genericSheetCancel: document.getElementById("genericSheetCancel"),
  toolBtns: [...document.querySelectorAll(".tool[data-tool]")],
  activeSwatch: document.getElementById("activeSwatch"),
  // 浮动色板
  colorPanel: document.getElementById("colorPanel"),
  colorPanelHead: document.getElementById("colorPanelHead"),
  colorPanelClose: document.getElementById("colorPanelClose"),
  colorPanelBody: document.querySelector("#colorPanel .float-panel-body"),  // 色轮 Vue 组件挂载点
  // clear sheet
  clearSheet: document.getElementById("clearSheet"),
  clearBackdrop: document.getElementById("clearBackdrop"),
  // update toast
  updateToast: document.getElementById("updateToast"),
  updateReload: document.getElementById("updateToastReload"),
  updateDismiss: document.getElementById("updateToastDismiss"),
};
